return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "stand-nnm",
      "stand-nnm_left",
      "walk-nnm",
      "walk-nnm_left",
      "giddyup",
      "giddyup_left",
      "theme 1",
      "theme 1_left",
      "galla_dress",
      "galla_dress_left",
      "truck_drive",
      "truck_drive_left",
      "tree_buck",
      "applojock",
      "applojock_left",
      "pose",
      "pose_left",
      "lasso",
      "lasso_left",
      "lasso2",
      "lasso2_left",
      "conga start",
      "conga start_left",
      "conga",
      "conga_left",
      "hurdle",
      "hurdle_left",
      "sleep",
      "sleep_left",
      "rear",
      "rear_left",
      "giddyup_old",
      "giddyup_old_left",
      "gallop_old",
      "gallop_old_left",
      "crystallized",
      "crystallized_left",
      "breezie",
      "breezie_left",
      "banjo",
      "drag",
      "drag_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "stand-nnm",
      "stand-nnm_left",
      "walk-nnm",
      "walk-nnm_left",
      "giddyup",
      "giddyup_left",
      "theme 1",
      "theme 1_left",
      "galla_dress",
      "galla_dress_left",
      "truck_drive",
      "truck_drive_left",
      "tree_buck",
      "applojock",
      "applojock_left",
      "pose",
      "pose_left",
      "lasso",
      "lasso_left",
      "lasso2",
      "lasso2_left",
      "conga start",
      "conga start_left",
      "conga",
      "conga_left",
      "hurdle",
      "hurdle_left",
      "sleep",
      "sleep_left",
      "rear",
      "rear_left",
      "giddyup_old",
      "giddyup_old_left",
      "gallop_old",
      "gallop_old_left",
      "crystallized",
      "crystallized_left",
      "breezie",
      "breezie_left",
      "banjo",
      "drag",
      "drag_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
    },
    ["stand-nnm"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "walk-nnm",
      "walk-nnm_left",
      "giddyup",
      "giddyup_left",
      "theme 1",
      "theme 1_left",
      "galla_dress",
      "galla_dress_left",
      "truck_drive",
      "truck_drive_left",
      "tree_buck",
      "applojock",
      "applojock_left",
      "pose",
      "pose_left",
      "lasso",
      "lasso_left",
      "lasso2",
      "lasso2_left",
      "conga start",
      "conga start_left",
      "conga",
      "conga_left",
      "hurdle",
      "hurdle_left",
      "sleep",
      "sleep_left",
      "rear",
      "rear_left",
      "giddyup_old",
      "giddyup_old_left",
      "gallop_old",
      "gallop_old_left",
      "crystallized",
      "crystallized_left",
      "breezie",
      "breezie_left",
      "banjo",
      "drag",
      "drag_left",
    },
    ["stand-nnm_left"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "walk-nnm",
      "walk-nnm_left",
      "giddyup",
      "giddyup_left",
      "theme 1",
      "theme 1_left",
      "galla_dress",
      "galla_dress_left",
      "truck_drive",
      "truck_drive_left",
      "tree_buck",
      "applojock",
      "applojock_left",
      "pose",
      "pose_left",
      "lasso",
      "lasso_left",
      "lasso2",
      "lasso2_left",
      "conga start",
      "conga start_left",
      "conga",
      "conga_left",
      "hurdle",
      "hurdle_left",
      "sleep",
      "sleep_left",
      "rear",
      "rear_left",
      "giddyup_old",
      "giddyup_old_left",
      "gallop_old",
      "gallop_old_left",
      "crystallized",
      "crystallized_left",
      "breezie",
      "breezie_left",
      "banjo",
      "drag",
      "drag_left",
    },
    ["walk-nnm"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "gallop",
      "gallop_left",
    },
    ["walk-nnm_left"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "gallop",
      "gallop_left",
    },
    giddyup = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "gallop",
    },
    giddyup_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "gallop",
    },
    gallop = {
      "walk",
      "walk_left",
      "walk-nnm",
      "walk-nnm_left",
    },
    gallop_left = {
      "walk",
      "walk_left",
      "walk-nnm",
      "walk-nnm_left",
    },
    ["theme 1"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    ["theme 1_left"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    galla_dress = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    galla_dress_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    truck_drive = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    truck_drive_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    tree_buck = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    applojock = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    applojock_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    pose = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    pose_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    lasso = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    lasso_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    lasso2 = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "Lasso",
    },
    lasso2_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "Lasso",
    },
    ["conga start"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "Conga",
    },
    ["conga start_left"] = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "Conga",
    },
    conga = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    conga_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    hurdle = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    hurdle_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    sleep = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    sleep_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    rear = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    rear_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    giddyup_old = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "gallop_old",
    },
    giddyup_old_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
      "gallop_old",
    },
    gallop_old = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    gallop_old_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    crystallized = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    crystallized_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    breezie = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    breezie_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    banjo = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    drag = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
    drag_left = {
      "stand",
      "stand_left",
      "stand-nnm",
      "stand-nnm_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "stand-nnm",
    "stand-nnm_left",
    "walk-nnm",
    "walk-nnm_left",
    "giddyup",
    "giddyup_left",
    "theme 1",
    "theme 1_left",
    "galla_dress",
    "galla_dress_left",
    "truck_drive",
    "truck_drive_left",
    "tree_buck",
    "applojock",
    "applojock_left",
    "pose",
    "pose_left",
    "lasso",
    "lasso_left",
    "lasso2",
    "lasso2_left",
    "conga start",
    "conga start_left",
    "conga",
    "conga_left",
    "hurdle",
    "hurdle_left",
    "sleep",
    "sleep_left",
    "rear",
    "rear_left",
    "giddyup_old",
    "giddyup_old_left",
    "gallop_old",
    "gallop_old_left",
    "crystallized",
    "crystallized_left",
    "breezie",
    "breezie_left",
    "banjo",
    "drag",
    "drag_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "gallop",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}