return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
      "sitting",
      "sitting_left",
      "drink",
      "drink_left",
      "drink 2",
      "drink 2_left",
      "stand2",
      "stand2_left",
      "fly2",
      "fly2_left",
      "walk2",
      "walk2_left",
      "sitting2",
      "sitting2_left",
      "sleep",
      "sleep_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
      "sitting",
      "sitting_left",
      "drink",
      "drink_left",
      "drink 2",
      "drink 2_left",
      "stand2",
      "stand2_left",
      "fly2",
      "fly2_left",
      "walk2",
      "walk2_left",
      "sitting2",
      "sitting2_left",
      "sleep",
      "sleep_left",
    },
    fly = {
      "stand",
      "stand_left",
    },
    fly_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    sitting = {
      "stand",
      "stand_left",
    },
    sitting_left = {
      "stand",
      "stand_left",
    },
    drink = {
      "stand",
      "stand_left",
    },
    drink_left = {
      "stand",
      "stand_left",
    },
    ["drink 2"] = {
      "stand",
      "stand_left",
      "stand2",
    },
    ["drink 2_left"] = {
      "stand",
      "stand_left",
      "stand2",
    },
    stand2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "fly2",
      "fly2_left",
      "walk2",
      "walk2_left",
      "sitting2",
      "sitting2_left",
      "sleep",
      "sleep_left",
    },
    stand2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "fly2",
      "fly2_left",
      "walk2",
      "walk2_left",
      "sitting2",
      "sitting2_left",
      "sleep",
      "sleep_left",
    },
    fly2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    fly2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    walk2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    walk2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    sitting2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    sitting2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    sleep = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "walk",
    },
    sleep_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "walk",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "sitting",
    "sitting_left",
    "drink",
    "drink_left",
    "drink 2",
    "drink 2_left",
    "stand2",
    "stand2_left",
    "fly2",
    "fly2_left",
    "walk2",
    "walk2_left",
    "sitting2",
    "sitting2_left",
    "sleep",
    "sleep_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
        "walk",
      },
      fast = {
        "fly",
        "walk",
      },
      slow = {
        "fly",
        "walk",
      },
    },
    left = {
      normal = {
        "fly_left",
        "walk_left",
      },
      fast = {
        "fly_left",
        "walk_left",
      },
      slow = {
        "fly_left",
        "walk_left",
      },
    },
  },
}