return {
  next_actions = {
    failsafe = {},
    failsafe_left = {},
    stand = {
      "stand",
      "stand_left",
      "flight",
      "flight_left",
      "flutter",
      "flutter_left",
      "sit",
      "sit_left",
      "ch-transform-right",
      "ch-transform-left",
      "ch-transform-right1",
      "ch-transform-left1",
      "ch-transform-right2",
      "ch-transform-left2",
      "transform-twi-right",
      "transform-twi-left",
      "transform-aj-right",
      "transform-aj-left",
      "transform-rd-right",
      "transform-rd-left",
      "transform-ra-right",
      "transform-ra-left",
      "transform-fl-right",
      "transform-fl-left",
      "transform-pi-right",
      "transform-pi-left",
      "transform-twi-right1",
      "transform-twi-left1",
      "transform-aj-right1",
      "transform-aj-left1",
      "transform-rd-right1",
      "transform-rd-left1",
      "transform-ra-right1",
      "transform-ra-left1",
      "transform-fl-right1",
      "transform-fl-left1",
      "transform-pi-right1",
      "transform-pi-left1",
      "twi-transform-right",
      "twi-transform-left",
      "twi-transform-right1",
      "twi-transform-left1",
      "transform-twi-ch-right",
      "transform-twi-ch-left",
      "transform-twi-ch-right1",
      "transform-twi-ch-left1",
      "transform-twi-ch-right2",
      "transform-twi-ch-left2",
      "transform-twi-rd-right",
      "transform-twi-rd-left",
      "transform-twi-ra-right",
      "transform-twi-ra-left",
      "transform-twi-aj-right",
      "transform-twi-aj-left",
      "transform-twi-pi-right",
      "transform-twi-pi-left",
      "transform-twi-fl-right",
      "transform-twi-fl-left",
      "twi-stand",
      "twi-stand_left",
      "twi-trot",
      "twi-trot_left",
      "twi-drag",
      "twi-drag_left",
      "rd-transform-right",
      "rd-transform-left",
      "rd-transform-right1",
      "rd-transform-left1",
      "transform-rd-ch-right",
      "transform-rd-ch-left",
      "transform-rd-ch-right1",
      "transform-rd-ch-left1",
      "transform-rd-ch-right2",
      "transform-rd-ch-left2",
      "transform-rd-twi-right",
      "transform-rd-twi-left",
      "transform-rd-ra-right",
      "transform-rd-ra-left",
      "transform-rd-aj-right",
      "transform-rd-aj-left",
      "transform-rd-pi-right",
      "transform-rd-pi-left",
      "transform-rd-fl-right",
      "transform-rd-fl-left",
      "rd-stand",
      "rd-stand_left",
      "rd-walk",
      "rd-walk_left",
      "rd-flyzoom",
      "rd-flyzoom_left",
      "rd-drag",
      "rd-drag_left",
      "aj-transform-right",
      "aj-transform-left",
      "aj-transform-right1",
      "aj-transform-left1",
      "transform-aj-ch-right",
      "transform-aj-ch-left",
      "transform-aj-ch-right1",
      "transform-aj-ch-left1",
      "transform-aj-ch-right2",
      "transform-aj-ch-left2",
      "transform-aj-twi-right",
      "transform-aj-twi-left",
      "transform-aj-rd-right",
      "transform-aj-rd-left",
      "transform-aj-ra-right",
      "transform-aj-ra-left",
      "transform-aj-pi-right",
      "transform-aj-pi-left",
      "transform-aj-fl-right",
      "transform-aj-fl-left",
      "aj-stand",
      "aj-stand_left",
      "aj-walk",
      "aj-walk_left",
      "aj-gallop",
      "aj-gallop_left",
      "aj-drag",
      "aj-drag_left",
      "pi-transform-right",
      "pi-transform-left",
      "pi-transform-right1",
      "pi-transform-left1",
      "transform-pi-ch-right",
      "transform-pi-ch-left",
      "transform-pi-ch-right1",
      "transform-pi-ch-left1",
      "transform-pi-ch-right2",
      "transform-pi-ch-left2",
      "transform-pi-twi-right",
      "transform-pi-twi-left",
      "transform-pi-rd-right",
      "transform-pi-rd-left",
      "transform-pi-aj-right",
      "transform-pi-aj-left",
      "transform-pi-ra-right",
      "transform-pi-ra-left",
      "transform-pi-fl-right",
      "transform-pi-fl-left",
      "pinkie-stand",
      "pinkie-stand_left",
      "pinkie-walk",
      "pinkie-walk_left",
      "pinkie-bounce",
      "pinkie-bounce_left",
      "pinkie-mouseover",
      "pinkie-mouseover_left",
      "pinkie-drag",
      "pinkie-drag_left",
      "pinkie-galopp",
      "pinkie-galopp_left",
      "ra-transform-right",
      "ra-transform-left",
      "ra-transform-right1",
      "ra-transform-left1",
      "transform-ra-ch-right",
      "transform-ra-ch-left",
      "transform-ra-ch-right1",
      "transform-ra-ch-left1",
      "transform-ra-ch-right2",
      "transform-ra-ch-left2",
      "transform-ra-twi-right",
      "transform-ra-twi-left",
      "transform-ra-rd-right",
      "transform-ra-rd-left",
      "transform-ra-aj-right",
      "transform-ra-aj-left",
      "transform-ra-pi-right",
      "transform-ra-pi-left",
      "transform-ra-fl-right",
      "transform-ra-fl-left",
      "rarity-stand",
      "rarity-stand_left",
      "rarity-walk",
      "rarity-walk_left",
      "rarity-drag",
      "rarity-drag_left",
      "fl-transform-right",
      "fl-transform-left",
      "fl-transform-right1",
      "fl-transform-left1",
      "transform-fl-ch-right",
      "transform-fl-ch-left",
      "transform-fl-ch-right1",
      "transform-fl-ch-left1",
      "transform-fl-ch-right2",
      "transform-fl-ch-left2",
      "transform-fl-twi-right",
      "transform-fl-twi-left",
      "transform-fl-rd-right",
      "transform-fl-rd-left",
      "transform-fl-aj-right",
      "transform-fl-aj-left",
      "transform-fl-ra-right",
      "transform-fl-ra-left",
      "transform-fl-pi-right",
      "transform-fl-pi-left",
      "flutter-stand",
      "flutter-stand_left",
      "flutter-mouseover",
      "flutter-mouseover_left",
      "flutter-drag",
      "flutter-drag_left",
      "flutter-walk",
      "flutter-walk_left",
      "flutter-fly",
      "flutter-fly_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "flight",
      "flight_left",
      "flutter",
      "flutter_left",
      "sit",
      "sit_left",
      "ch-transform-right",
      "ch-transform-left",
      "ch-transform-right1",
      "ch-transform-left1",
      "ch-transform-right2",
      "ch-transform-left2",
      "transform-twi-right",
      "transform-twi-left",
      "transform-aj-right",
      "transform-aj-left",
      "transform-rd-right",
      "transform-rd-left",
      "transform-ra-right",
      "transform-ra-left",
      "transform-fl-right",
      "transform-fl-left",
      "transform-pi-right",
      "transform-pi-left",
      "transform-twi-right1",
      "transform-twi-left1",
      "transform-aj-right1",
      "transform-aj-left1",
      "transform-rd-right1",
      "transform-rd-left1",
      "transform-ra-right1",
      "transform-ra-left1",
      "transform-fl-right1",
      "transform-fl-left1",
      "transform-pi-right1",
      "transform-pi-left1",
      "twi-transform-right",
      "twi-transform-left",
      "twi-transform-right1",
      "twi-transform-left1",
      "transform-twi-ch-right",
      "transform-twi-ch-left",
      "transform-twi-ch-right1",
      "transform-twi-ch-left1",
      "transform-twi-ch-right2",
      "transform-twi-ch-left2",
      "transform-twi-rd-right",
      "transform-twi-rd-left",
      "transform-twi-ra-right",
      "transform-twi-ra-left",
      "transform-twi-aj-right",
      "transform-twi-aj-left",
      "transform-twi-pi-right",
      "transform-twi-pi-left",
      "transform-twi-fl-right",
      "transform-twi-fl-left",
      "twi-stand",
      "twi-stand_left",
      "twi-trot",
      "twi-trot_left",
      "twi-drag",
      "twi-drag_left",
      "rd-transform-right",
      "rd-transform-left",
      "rd-transform-right1",
      "rd-transform-left1",
      "transform-rd-ch-right",
      "transform-rd-ch-left",
      "transform-rd-ch-right1",
      "transform-rd-ch-left1",
      "transform-rd-ch-right2",
      "transform-rd-ch-left2",
      "transform-rd-twi-right",
      "transform-rd-twi-left",
      "transform-rd-ra-right",
      "transform-rd-ra-left",
      "transform-rd-aj-right",
      "transform-rd-aj-left",
      "transform-rd-pi-right",
      "transform-rd-pi-left",
      "transform-rd-fl-right",
      "transform-rd-fl-left",
      "rd-stand",
      "rd-stand_left",
      "rd-walk",
      "rd-walk_left",
      "rd-flyzoom",
      "rd-flyzoom_left",
      "rd-drag",
      "rd-drag_left",
      "aj-transform-right",
      "aj-transform-left",
      "aj-transform-right1",
      "aj-transform-left1",
      "transform-aj-ch-right",
      "transform-aj-ch-left",
      "transform-aj-ch-right1",
      "transform-aj-ch-left1",
      "transform-aj-ch-right2",
      "transform-aj-ch-left2",
      "transform-aj-twi-right",
      "transform-aj-twi-left",
      "transform-aj-rd-right",
      "transform-aj-rd-left",
      "transform-aj-ra-right",
      "transform-aj-ra-left",
      "transform-aj-pi-right",
      "transform-aj-pi-left",
      "transform-aj-fl-right",
      "transform-aj-fl-left",
      "aj-stand",
      "aj-stand_left",
      "aj-walk",
      "aj-walk_left",
      "aj-gallop",
      "aj-gallop_left",
      "aj-drag",
      "aj-drag_left",
      "pi-transform-right",
      "pi-transform-left",
      "pi-transform-right1",
      "pi-transform-left1",
      "transform-pi-ch-right",
      "transform-pi-ch-left",
      "transform-pi-ch-right1",
      "transform-pi-ch-left1",
      "transform-pi-ch-right2",
      "transform-pi-ch-left2",
      "transform-pi-twi-right",
      "transform-pi-twi-left",
      "transform-pi-rd-right",
      "transform-pi-rd-left",
      "transform-pi-aj-right",
      "transform-pi-aj-left",
      "transform-pi-ra-right",
      "transform-pi-ra-left",
      "transform-pi-fl-right",
      "transform-pi-fl-left",
      "pinkie-stand",
      "pinkie-stand_left",
      "pinkie-walk",
      "pinkie-walk_left",
      "pinkie-bounce",
      "pinkie-bounce_left",
      "pinkie-mouseover",
      "pinkie-mouseover_left",
      "pinkie-drag",
      "pinkie-drag_left",
      "pinkie-galopp",
      "pinkie-galopp_left",
      "ra-transform-right",
      "ra-transform-left",
      "ra-transform-right1",
      "ra-transform-left1",
      "transform-ra-ch-right",
      "transform-ra-ch-left",
      "transform-ra-ch-right1",
      "transform-ra-ch-left1",
      "transform-ra-ch-right2",
      "transform-ra-ch-left2",
      "transform-ra-twi-right",
      "transform-ra-twi-left",
      "transform-ra-rd-right",
      "transform-ra-rd-left",
      "transform-ra-aj-right",
      "transform-ra-aj-left",
      "transform-ra-pi-right",
      "transform-ra-pi-left",
      "transform-ra-fl-right",
      "transform-ra-fl-left",
      "rarity-stand",
      "rarity-stand_left",
      "rarity-walk",
      "rarity-walk_left",
      "rarity-drag",
      "rarity-drag_left",
      "fl-transform-right",
      "fl-transform-left",
      "fl-transform-right1",
      "fl-transform-left1",
      "transform-fl-ch-right",
      "transform-fl-ch-left",
      "transform-fl-ch-right1",
      "transform-fl-ch-left1",
      "transform-fl-ch-right2",
      "transform-fl-ch-left2",
      "transform-fl-twi-right",
      "transform-fl-twi-left",
      "transform-fl-rd-right",
      "transform-fl-rd-left",
      "transform-fl-aj-right",
      "transform-fl-aj-left",
      "transform-fl-ra-right",
      "transform-fl-ra-left",
      "transform-fl-pi-right",
      "transform-fl-pi-left",
      "flutter-stand",
      "flutter-stand_left",
      "flutter-mouseover",
      "flutter-mouseover_left",
      "flutter-drag",
      "flutter-drag_left",
      "flutter-walk",
      "flutter-walk_left",
      "flutter-fly",
      "flutter-fly_left",
    },
    trot = {},
    trot_left = {},
    flight = {
      "stand",
      "stand_left",
    },
    flight_left = {
      "stand",
      "stand_left",
    },
    flutter = {
      "stand",
      "stand_left",
    },
    flutter_left = {
      "stand",
      "stand_left",
    },
    sit = {
      "stand",
      "stand_left",
    },
    sit_left = {
      "stand",
      "stand_left",
    },
    ["ch-transform-right"] = {
      "stand",
      "stand_left",
    },
    ["ch-transform-left"] = {
      "stand",
      "stand_left",
    },
    ["ch-transform-right1"] = {
      "stand",
      "stand_left",
      "trot",
    },
    ["ch-transform-left1"] = {
      "stand",
      "stand_left",
      "trot",
    },
    ["ch-transform-right2"] = {
      "stand",
      "stand_left",
      "flight",
    },
    ["ch-transform-left2"] = {
      "stand",
      "stand_left",
      "flight",
    },
    ["transform-twi-right"] = {
      "stand",
      "stand_left",
      "twi-transform-right",
    },
    ["transform-twi-left"] = {
      "stand",
      "stand_left",
      "twi-transform-left",
    },
    ["transform-aj-right"] = {
      "stand",
      "stand_left",
      "aj-transform-right",
    },
    ["transform-aj-left"] = {
      "stand",
      "stand_left",
      "aj-transform-left",
    },
    ["transform-rd-right"] = {
      "stand",
      "stand_left",
      "rd-transform-right",
    },
    ["transform-rd-left"] = {
      "stand",
      "stand_left",
      "rd-transform-left",
    },
    ["transform-ra-right"] = {
      "stand",
      "stand_left",
      "ra-transform-right",
    },
    ["transform-ra-left"] = {
      "stand",
      "stand_left",
      "ra-transform-left",
    },
    ["transform-fl-right"] = {
      "stand",
      "stand_left",
      "fl-transform-right",
    },
    ["transform-fl-left"] = {
      "stand",
      "stand_left",
      "fl-transform-left",
    },
    ["transform-pi-right"] = {
      "stand",
      "stand_left",
      "pi-transform-right",
    },
    ["transform-pi-left"] = {
      "stand",
      "stand_left",
      "pi-transform-left",
    },
    ["transform-twi-right1"] = {
      "stand",
      "stand_left",
      "twi-transform-right1",
    },
    ["transform-twi-left1"] = {
      "stand",
      "stand_left",
      "twi-transform-left1",
    },
    ["transform-aj-right1"] = {
      "stand",
      "stand_left",
      "aj-transform-right1",
    },
    ["transform-aj-left1"] = {
      "stand",
      "stand_left",
      "aj-transform-left1",
    },
    ["transform-rd-right1"] = {
      "stand",
      "stand_left",
      "rd-transform-right1",
    },
    ["transform-rd-left1"] = {
      "stand",
      "stand_left",
      "rd-transform-left1",
    },
    ["transform-ra-right1"] = {
      "stand",
      "stand_left",
      "ra-transform-right1",
    },
    ["transform-ra-left1"] = {
      "stand",
      "stand_left",
      "ra-transform-left1",
    },
    ["transform-fl-right1"] = {
      "stand",
      "stand_left",
      "fl-transform-right1",
    },
    ["transform-fl-left1"] = {
      "stand",
      "stand_left",
      "fl-transform-left1",
    },
    ["transform-pi-right1"] = {
      "stand",
      "stand_left",
      "pi-transform-right1",
    },
    ["transform-pi-left1"] = {
      "stand",
      "stand_left",
      "pi-transform-left1",
    },
    ["twi-transform-right"] = {
      "stand",
      "stand_left",
      "twi-stand",
    },
    ["twi-transform-left"] = {
      "stand",
      "stand_left",
      "twi-stand",
    },
    ["twi-transform-right1"] = {
      "stand",
      "stand_left",
      "twi-trot",
    },
    ["twi-transform-left1"] = {
      "stand",
      "stand_left",
      "twi-trot",
    },
    ["transform-twi-ch-right"] = {
      "stand",
      "stand_left",
      "ch-transform-right",
    },
    ["transform-twi-ch-left"] = {
      "stand",
      "stand_left",
      "ch-transform-left",
    },
    ["transform-twi-ch-right1"] = {
      "stand",
      "stand_left",
      "ch-transform-right1",
    },
    ["transform-twi-ch-left1"] = {
      "stand",
      "stand_left",
      "ch-transform-left1",
    },
    ["transform-twi-ch-right2"] = {
      "stand",
      "stand_left",
      "ch-transform-right2",
    },
    ["transform-twi-ch-left2"] = {
      "stand",
      "stand_left",
      "ch-transform-left2",
    },
    ["transform-twi-rd-right"] = {
      "stand",
      "stand_left",
      "rd-transform-right1",
    },
    ["transform-twi-rd-left"] = {
      "stand",
      "stand_left",
      "rd-transform-left1",
    },
    ["transform-twi-ra-right"] = {
      "stand",
      "stand_left",
      "ra-transform-right1",
    },
    ["transform-twi-ra-left"] = {
      "stand",
      "stand_left",
      "ra-transform-left1",
    },
    ["transform-twi-aj-right"] = {
      "stand",
      "stand_left",
      "aj-transform-right1",
    },
    ["transform-twi-aj-left"] = {
      "stand",
      "stand_left",
      "aj-transform-left1",
    },
    ["transform-twi-pi-right"] = {
      "stand",
      "stand_left",
      "pi-transform-right1",
    },
    ["transform-twi-pi-left"] = {
      "stand",
      "stand_left",
      "pi-transform-left1",
    },
    ["transform-twi-fl-right"] = {
      "stand",
      "stand_left",
      "fl-transform-right1",
    },
    ["transform-twi-fl-left"] = {
      "stand",
      "stand_left",
      "fl-transform-left1",
    },
    ["twi-stand"] = {
      "stand",
      "stand_left",
    },
    ["twi-stand_left"] = {
      "stand",
      "stand_left",
    },
    ["twi-trot"] = {
      "stand",
      "stand_left",
    },
    ["twi-trot_left"] = {
      "stand",
      "stand_left",
    },
    ["twi-drag"] = {
      "stand",
      "stand_left",
    },
    ["twi-drag_left"] = {
      "stand",
      "stand_left",
    },
    ["rd-transform-right"] = {
      "stand",
      "stand_left",
      "rd-stand",
    },
    ["rd-transform-left"] = {
      "stand",
      "stand_left",
      "rd-stand",
    },
    ["rd-transform-right1"] = {
      "stand",
      "stand_left",
      "rd-walk",
    },
    ["rd-transform-left1"] = {
      "stand",
      "stand_left",
      "rd-walk",
    },
    ["transform-rd-ch-right"] = {
      "stand",
      "stand_left",
      "ch-transform-right",
    },
    ["transform-rd-ch-left"] = {
      "stand",
      "stand_left",
      "ch-transform-left",
    },
    ["transform-rd-ch-right1"] = {
      "stand",
      "stand_left",
      "ch-transform-right1",
    },
    ["transform-rd-ch-left1"] = {
      "stand",
      "stand_left",
      "ch-transform-left1",
    },
    ["transform-rd-ch-right2"] = {
      "stand",
      "stand_left",
      "ch-transform-right2",
    },
    ["transform-rd-ch-left2"] = {
      "stand",
      "stand_left",
      "ch-transform-left2",
    },
    ["transform-rd-twi-right"] = {
      "stand",
      "stand_left",
      "twi-transform-right1",
    },
    ["transform-rd-twi-left"] = {
      "stand",
      "stand_left",
      "twi-transform-left1",
    },
    ["transform-rd-ra-right"] = {
      "stand",
      "stand_left",
      "ra-transform-right1",
    },
    ["transform-rd-ra-left"] = {
      "stand",
      "stand_left",
      "ra-transform-left1",
    },
    ["transform-rd-aj-right"] = {
      "stand",
      "stand_left",
      "aj-transform-right1",
    },
    ["transform-rd-aj-left"] = {
      "stand",
      "stand_left",
      "aj-transform-left1",
    },
    ["transform-rd-pi-right"] = {
      "stand",
      "stand_left",
      "pi-transform-right1",
    },
    ["transform-rd-pi-left"] = {
      "stand",
      "stand_left",
      "pi-transform-left1",
    },
    ["transform-rd-fl-right"] = {
      "stand",
      "stand_left",
      "fl-transform-right1",
    },
    ["transform-rd-fl-left"] = {
      "stand",
      "stand_left",
      "fl-transform-left1",
    },
    ["rd-stand"] = {
      "stand",
      "stand_left",
    },
    ["rd-stand_left"] = {
      "stand",
      "stand_left",
    },
    ["rd-walk"] = {
      "stand",
      "stand_left",
    },
    ["rd-walk_left"] = {
      "stand",
      "stand_left",
    },
    ["rd-flyzoom"] = {
      "stand",
      "stand_left",
    },
    ["rd-flyzoom_left"] = {
      "stand",
      "stand_left",
    },
    ["rd-drag"] = {
      "stand",
      "stand_left",
    },
    ["rd-drag_left"] = {
      "stand",
      "stand_left",
    },
    ["aj-transform-right"] = {
      "stand",
      "stand_left",
      "aj-stand",
    },
    ["aj-transform-left"] = {
      "stand",
      "stand_left",
      "aj-stand",
    },
    ["aj-transform-right1"] = {
      "stand",
      "stand_left",
      "aj-walk",
    },
    ["aj-transform-left1"] = {
      "stand",
      "stand_left",
      "aj-walk",
    },
    ["transform-aj-ch-right"] = {
      "stand",
      "stand_left",
      "ch-transform-right",
    },
    ["transform-aj-ch-left"] = {
      "stand",
      "stand_left",
      "ch-transform-left",
    },
    ["transform-aj-ch-right1"] = {
      "stand",
      "stand_left",
      "ch-transform-right1",
    },
    ["transform-aj-ch-left1"] = {
      "stand",
      "stand_left",
      "ch-transform-left1",
    },
    ["transform-aj-ch-right2"] = {
      "stand",
      "stand_left",
      "ch-transform-right2",
    },
    ["transform-aj-ch-left2"] = {
      "stand",
      "stand_left",
      "ch-transform-left2",
    },
    ["transform-aj-twi-right"] = {
      "stand",
      "stand_left",
      "twi-transform-right1",
    },
    ["transform-aj-twi-left"] = {
      "stand",
      "stand_left",
      "twi-transform-left1",
    },
    ["transform-aj-rd-right"] = {
      "stand",
      "stand_left",
      "rd-transform-right1",
    },
    ["transform-aj-rd-left"] = {
      "stand",
      "stand_left",
      "rd-transform-left1",
    },
    ["transform-aj-ra-right"] = {
      "stand",
      "stand_left",
      "ra-transform-right1",
    },
    ["transform-aj-ra-left"] = {
      "stand",
      "stand_left",
      "ra-transform-left1",
    },
    ["transform-aj-pi-right"] = {
      "stand",
      "stand_left",
      "pi-transform-right1",
    },
    ["transform-aj-pi-left"] = {
      "stand",
      "stand_left",
      "pi-transform-left1",
    },
    ["transform-aj-fl-right"] = {
      "stand",
      "stand_left",
      "fl-transform-right1",
    },
    ["transform-aj-fl-left"] = {
      "stand",
      "stand_left",
      "fl-transform-left1",
    },
    ["aj-stand"] = {
      "stand",
      "stand_left",
    },
    ["aj-stand_left"] = {
      "stand",
      "stand_left",
    },
    ["aj-walk"] = {
      "stand",
      "stand_left",
    },
    ["aj-walk_left"] = {
      "stand",
      "stand_left",
    },
    ["aj-gallop"] = {
      "stand",
      "stand_left",
    },
    ["aj-gallop_left"] = {
      "stand",
      "stand_left",
    },
    ["aj-drag"] = {
      "stand",
      "stand_left",
    },
    ["aj-drag_left"] = {
      "stand",
      "stand_left",
    },
    ["pi-transform-right"] = {
      "stand",
      "stand_left",
      "pinkie-stand",
    },
    ["pi-transform-left"] = {
      "stand",
      "stand_left",
      "pinkie-stand",
    },
    ["pi-transform-right1"] = {
      "stand",
      "stand_left",
      "pinkie-bounce",
    },
    ["pi-transform-left1"] = {
      "stand",
      "stand_left",
      "pinkie-bounce",
    },
    ["transform-pi-ch-right"] = {
      "stand",
      "stand_left",
      "ch-transform-right",
    },
    ["transform-pi-ch-left"] = {
      "stand",
      "stand_left",
      "ch-transform-left",
    },
    ["transform-pi-ch-right1"] = {
      "stand",
      "stand_left",
      "ch-transform-right1",
    },
    ["transform-pi-ch-left1"] = {
      "stand",
      "stand_left",
      "ch-transform-left1",
    },
    ["transform-pi-ch-right2"] = {
      "stand",
      "stand_left",
      "ch-transform-right2",
    },
    ["transform-pi-ch-left2"] = {
      "stand",
      "stand_left",
      "ch-transform-left2",
    },
    ["transform-pi-twi-right"] = {
      "stand",
      "stand_left",
      "twi-transform-right1",
    },
    ["transform-pi-twi-left"] = {
      "stand",
      "stand_left",
      "twi-transform-left1",
    },
    ["transform-pi-rd-right"] = {
      "stand",
      "stand_left",
      "rd-transform-right1",
    },
    ["transform-pi-rd-left"] = {
      "stand",
      "stand_left",
      "rd-transform-left1",
    },
    ["transform-pi-aj-right"] = {
      "stand",
      "stand_left",
      "aj-transform-right1",
    },
    ["transform-pi-aj-left"] = {
      "stand",
      "stand_left",
      "aj-transform-left1",
    },
    ["transform-pi-ra-right"] = {
      "stand",
      "stand_left",
      "ra-transform-right1",
    },
    ["transform-pi-ra-left"] = {
      "stand",
      "stand_left",
      "ra-transform-left1",
    },
    ["transform-pi-fl-right"] = {
      "stand",
      "stand_left",
      "fl-transform-right1",
    },
    ["transform-pi-fl-left"] = {
      "stand",
      "stand_left",
      "fl-transform-left1",
    },
    ["pinkie-stand"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-stand_left"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-walk"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-walk_left"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-bounce"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-bounce_left"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-mouseover"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-mouseover_left"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-drag"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-drag_left"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-galopp"] = {
      "stand",
      "stand_left",
    },
    ["pinkie-galopp_left"] = {
      "stand",
      "stand_left",
    },
    ["ra-transform-right"] = {
      "stand",
      "stand_left",
      "rarity-stand",
    },
    ["ra-transform-left"] = {
      "stand",
      "stand_left",
      "rarity-stand",
    },
    ["ra-transform-right1"] = {
      "stand",
      "stand_left",
      "rarity-walk",
    },
    ["ra-transform-left1"] = {
      "stand",
      "stand_left",
      "rarity-walk",
    },
    ["transform-ra-ch-right"] = {
      "stand",
      "stand_left",
      "ch-transform-right",
    },
    ["transform-ra-ch-left"] = {
      "stand",
      "stand_left",
      "ch-transform-left",
    },
    ["transform-ra-ch-right1"] = {
      "stand",
      "stand_left",
      "ch-transform-right1",
    },
    ["transform-ra-ch-left1"] = {
      "stand",
      "stand_left",
      "ch-transform-left1",
    },
    ["transform-ra-ch-right2"] = {
      "stand",
      "stand_left",
      "ch-transform-right2",
    },
    ["transform-ra-ch-left2"] = {
      "stand",
      "stand_left",
      "ch-transform-left2",
    },
    ["transform-ra-twi-right"] = {
      "stand",
      "stand_left",
      "twi-transform-right1",
    },
    ["transform-ra-twi-left"] = {
      "stand",
      "stand_left",
      "twi-transform-left1",
    },
    ["transform-ra-rd-right"] = {
      "stand",
      "stand_left",
      "rd-transform-right1",
    },
    ["transform-ra-rd-left"] = {
      "stand",
      "stand_left",
      "rd-transform-left1",
    },
    ["transform-ra-aj-right"] = {
      "stand",
      "stand_left",
      "aj-transform-right1",
    },
    ["transform-ra-aj-left"] = {
      "stand",
      "stand_left",
      "aj-transform-left1",
    },
    ["transform-ra-pi-right"] = {
      "stand",
      "stand_left",
      "pi-transform-right1",
    },
    ["transform-ra-pi-left"] = {
      "stand",
      "stand_left",
      "pi-transform-left1",
    },
    ["transform-ra-fl-right"] = {
      "stand",
      "stand_left",
      "fl-transform-right1",
    },
    ["transform-ra-fl-left"] = {
      "stand",
      "stand_left",
      "fl-transform-left1",
    },
    ["rarity-stand"] = {
      "stand",
      "stand_left",
    },
    ["rarity-stand_left"] = {
      "stand",
      "stand_left",
    },
    ["rarity-walk"] = {
      "stand",
      "stand_left",
    },
    ["rarity-walk_left"] = {
      "stand",
      "stand_left",
    },
    ["rarity-drag"] = {
      "stand",
      "stand_left",
    },
    ["rarity-drag_left"] = {
      "stand",
      "stand_left",
    },
    ["fl-transform-right"] = {
      "stand",
      "stand_left",
      "flutter-stand",
    },
    ["fl-transform-left"] = {
      "stand",
      "stand_left",
      "flutter-stand",
    },
    ["fl-transform-right1"] = {
      "stand",
      "stand_left",
      "flutter-fly",
    },
    ["fl-transform-left1"] = {
      "stand",
      "stand_left",
      "flutter-fly",
    },
    ["transform-fl-ch-right"] = {
      "stand",
      "stand_left",
      "ch-transform-right",
    },
    ["transform-fl-ch-left"] = {
      "stand",
      "stand_left",
      "ch-transform-left",
    },
    ["transform-fl-ch-right1"] = {
      "stand",
      "stand_left",
      "ch-transform-right1",
    },
    ["transform-fl-ch-left1"] = {
      "stand",
      "stand_left",
      "ch-transform-left1",
    },
    ["transform-fl-ch-right2"] = {
      "stand",
      "stand_left",
      "ch-transform-right2",
    },
    ["transform-fl-ch-left2"] = {
      "stand",
      "stand_left",
      "ch-transform-left2",
    },
    ["transform-fl-twi-right"] = {
      "stand",
      "stand_left",
      "twi-transform-right1",
    },
    ["transform-fl-twi-left"] = {
      "stand",
      "stand_left",
      "twi-transform-left1",
    },
    ["transform-fl-rd-right"] = {
      "stand",
      "stand_left",
      "rd-transform-right1",
    },
    ["transform-fl-rd-left"] = {
      "stand",
      "stand_left",
      "rd-transform-left1",
    },
    ["transform-fl-aj-right"] = {
      "stand",
      "stand_left",
      "aj-transform-right1",
    },
    ["transform-fl-aj-left"] = {
      "stand",
      "stand_left",
      "aj-transform-left1",
    },
    ["transform-fl-ra-right"] = {
      "stand",
      "stand_left",
      "ra-transform-right1",
    },
    ["transform-fl-ra-left"] = {
      "stand",
      "stand_left",
      "ra-transform-left1",
    },
    ["transform-fl-pi-right"] = {
      "stand",
      "stand_left",
      "pi-transform-right1",
    },
    ["transform-fl-pi-left"] = {
      "stand",
      "stand_left",
      "pi-transform-left1",
    },
    ["flutter-stand"] = {
      "stand",
      "stand_left",
    },
    ["flutter-stand_left"] = {
      "stand",
      "stand_left",
    },
    ["flutter-mouseover"] = {
      "stand",
      "stand_left",
    },
    ["flutter-mouseover_left"] = {
      "stand",
      "stand_left",
    },
    ["flutter-drag"] = {
      "stand",
      "stand_left",
    },
    ["flutter-drag_left"] = {
      "stand",
      "stand_left",
    },
    ["flutter-walk"] = {
      "stand",
      "stand_left",
    },
    ["flutter-walk_left"] = {
      "stand",
      "stand_left",
    },
    ["flutter-fly"] = {
      "stand",
      "stand_left",
    },
    ["flutter-fly_left"] = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "failsafe",
    "failsafe_left",
    "stand",
    "stand_left",
    "flight",
    "flight_left",
    "flutter",
    "flutter_left",
    "sit",
    "sit_left",
    "ch-transform-right",
    "ch-transform-left",
    "ch-transform-right1",
    "ch-transform-left1",
    "ch-transform-right2",
    "ch-transform-left2",
    "transform-twi-right",
    "transform-twi-left",
    "transform-aj-right",
    "transform-aj-left",
    "transform-rd-right",
    "transform-rd-left",
    "transform-ra-right",
    "transform-ra-left",
    "transform-fl-right",
    "transform-fl-left",
    "transform-pi-right",
    "transform-pi-left",
    "transform-twi-right1",
    "transform-twi-left1",
    "transform-aj-right1",
    "transform-aj-left1",
    "transform-rd-right1",
    "transform-rd-left1",
    "transform-ra-right1",
    "transform-ra-left1",
    "transform-fl-right1",
    "transform-fl-left1",
    "transform-pi-right1",
    "transform-pi-left1",
    "twi-transform-right",
    "twi-transform-left",
    "twi-transform-right1",
    "twi-transform-left1",
    "transform-twi-ch-right",
    "transform-twi-ch-left",
    "transform-twi-ch-right1",
    "transform-twi-ch-left1",
    "transform-twi-ch-right2",
    "transform-twi-ch-left2",
    "transform-twi-rd-right",
    "transform-twi-rd-left",
    "transform-twi-ra-right",
    "transform-twi-ra-left",
    "transform-twi-aj-right",
    "transform-twi-aj-left",
    "transform-twi-pi-right",
    "transform-twi-pi-left",
    "transform-twi-fl-right",
    "transform-twi-fl-left",
    "twi-stand",
    "twi-stand_left",
    "twi-trot",
    "twi-trot_left",
    "twi-drag",
    "twi-drag_left",
    "rd-transform-right",
    "rd-transform-left",
    "rd-transform-right1",
    "rd-transform-left1",
    "transform-rd-ch-right",
    "transform-rd-ch-left",
    "transform-rd-ch-right1",
    "transform-rd-ch-left1",
    "transform-rd-ch-right2",
    "transform-rd-ch-left2",
    "transform-rd-twi-right",
    "transform-rd-twi-left",
    "transform-rd-ra-right",
    "transform-rd-ra-left",
    "transform-rd-aj-right",
    "transform-rd-aj-left",
    "transform-rd-pi-right",
    "transform-rd-pi-left",
    "transform-rd-fl-right",
    "transform-rd-fl-left",
    "rd-stand",
    "rd-stand_left",
    "rd-walk",
    "rd-walk_left",
    "rd-flyzoom",
    "rd-flyzoom_left",
    "rd-drag",
    "rd-drag_left",
    "aj-transform-right",
    "aj-transform-left",
    "aj-transform-right1",
    "aj-transform-left1",
    "transform-aj-ch-right",
    "transform-aj-ch-left",
    "transform-aj-ch-right1",
    "transform-aj-ch-left1",
    "transform-aj-ch-right2",
    "transform-aj-ch-left2",
    "transform-aj-twi-right",
    "transform-aj-twi-left",
    "transform-aj-rd-right",
    "transform-aj-rd-left",
    "transform-aj-ra-right",
    "transform-aj-ra-left",
    "transform-aj-pi-right",
    "transform-aj-pi-left",
    "transform-aj-fl-right",
    "transform-aj-fl-left",
    "aj-stand",
    "aj-stand_left",
    "aj-walk",
    "aj-walk_left",
    "aj-gallop",
    "aj-gallop_left",
    "aj-drag",
    "aj-drag_left",
    "pi-transform-right",
    "pi-transform-left",
    "pi-transform-right1",
    "pi-transform-left1",
    "transform-pi-ch-right",
    "transform-pi-ch-left",
    "transform-pi-ch-right1",
    "transform-pi-ch-left1",
    "transform-pi-ch-right2",
    "transform-pi-ch-left2",
    "transform-pi-twi-right",
    "transform-pi-twi-left",
    "transform-pi-rd-right",
    "transform-pi-rd-left",
    "transform-pi-aj-right",
    "transform-pi-aj-left",
    "transform-pi-ra-right",
    "transform-pi-ra-left",
    "transform-pi-fl-right",
    "transform-pi-fl-left",
    "pinkie-stand",
    "pinkie-stand_left",
    "pinkie-walk",
    "pinkie-walk_left",
    "pinkie-bounce",
    "pinkie-bounce_left",
    "pinkie-mouseover",
    "pinkie-mouseover_left",
    "pinkie-drag",
    "pinkie-drag_left",
    "pinkie-galopp",
    "pinkie-galopp_left",
    "ra-transform-right",
    "ra-transform-left",
    "ra-transform-right1",
    "ra-transform-left1",
    "transform-ra-ch-right",
    "transform-ra-ch-left",
    "transform-ra-ch-right1",
    "transform-ra-ch-left1",
    "transform-ra-ch-right2",
    "transform-ra-ch-left2",
    "transform-ra-twi-right",
    "transform-ra-twi-left",
    "transform-ra-rd-right",
    "transform-ra-rd-left",
    "transform-ra-aj-right",
    "transform-ra-aj-left",
    "transform-ra-pi-right",
    "transform-ra-pi-left",
    "transform-ra-fl-right",
    "transform-ra-fl-left",
    "rarity-stand",
    "rarity-stand_left",
    "rarity-walk",
    "rarity-walk_left",
    "rarity-drag",
    "rarity-drag_left",
    "fl-transform-right",
    "fl-transform-left",
    "fl-transform-right1",
    "fl-transform-left1",
    "transform-fl-ch-right",
    "transform-fl-ch-left",
    "transform-fl-ch-right1",
    "transform-fl-ch-left1",
    "transform-fl-ch-right2",
    "transform-fl-ch-left2",
    "transform-fl-twi-right",
    "transform-fl-twi-left",
    "transform-fl-rd-right",
    "transform-fl-rd-left",
    "transform-fl-aj-right",
    "transform-fl-aj-left",
    "transform-fl-ra-right",
    "transform-fl-ra-left",
    "transform-fl-pi-right",
    "transform-fl-pi-left",
    "flutter-stand",
    "flutter-stand_left",
    "flutter-mouseover",
    "flutter-mouseover_left",
    "flutter-drag",
    "flutter-drag_left",
    "flutter-walk",
    "flutter-walk_left",
    "flutter-fly",
    "flutter-fly_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {},
      fast = {
        "gallop",
      },
      slow = {},
    },
    left = {
      normal = {
        "gallop_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {},
    },
  },
}