return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "walk_wing",
      "walk_wing_left",
      "fly",
      "fly_left",
      "hover_still",
      "hover_still_left",
      "fly_derp",
      "fly_derp_left",
      "hover_derp",
      "hover_derp_left",
      "grab_mail",
      "grab_mail_left",
      "fly_mail_1",
      "fly_mail_1_left",
      "fly_mail_2",
      "fly_mail_2_left",
      "fly_mail_3",
      "fly_mail_3_left",
      "putaway_mail",
      "putaway_mail_left",
      "muffin",
      "muffin_left",
      "sit",
      "sit_left",
      "drag",
      "drag_left",
      "cloud_start",
      "cloud_start_left",
      "cloud_bounce",
      "cloud_bounce_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "walk_wing",
      "walk_wing_left",
      "fly",
      "fly_left",
      "hover_still",
      "hover_still_left",
      "fly_derp",
      "fly_derp_left",
      "hover_derp",
      "hover_derp_left",
      "grab_mail",
      "grab_mail_left",
      "fly_mail_1",
      "fly_mail_1_left",
      "fly_mail_2",
      "fly_mail_2_left",
      "fly_mail_3",
      "fly_mail_3_left",
      "putaway_mail",
      "putaway_mail_left",
      "muffin",
      "muffin_left",
      "sit",
      "sit_left",
      "drag",
      "drag_left",
      "cloud_start",
      "cloud_start_left",
      "cloud_bounce",
      "cloud_bounce_left",
    },
    stand_wing = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "walk_wing",
      "walk_wing_left",
      "fly",
      "fly_left",
      "hover_still",
      "hover_still_left",
      "fly_derp",
      "fly_derp_left",
      "hover_derp",
      "hover_derp_left",
      "grab_mail",
      "grab_mail_left",
      "fly_mail_1",
      "fly_mail_1_left",
      "fly_mail_2",
      "fly_mail_2_left",
      "fly_mail_3",
      "fly_mail_3_left",
      "putaway_mail",
      "putaway_mail_left",
      "muffin",
      "muffin_left",
      "sit",
      "sit_left",
      "drag",
      "drag_left",
      "cloud_start",
      "cloud_start_left",
      "cloud_bounce",
      "cloud_bounce_left",
    },
    stand_wing_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "walk_wing",
      "walk_wing_left",
      "fly",
      "fly_left",
      "hover_still",
      "hover_still_left",
      "fly_derp",
      "fly_derp_left",
      "hover_derp",
      "hover_derp_left",
      "grab_mail",
      "grab_mail_left",
      "fly_mail_1",
      "fly_mail_1_left",
      "fly_mail_2",
      "fly_mail_2_left",
      "fly_mail_3",
      "fly_mail_3_left",
      "putaway_mail",
      "putaway_mail_left",
      "muffin",
      "muffin_left",
      "sit",
      "sit_left",
      "drag",
      "drag_left",
      "cloud_start",
      "cloud_start_left",
      "cloud_bounce",
      "cloud_bounce_left",
    },
    sleep = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    sleep_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    walk = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    walk_wing = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly",
      "fly_left",
    },
    walk_wing_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly",
      "fly_left",
    },
    fly = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "walk",
      "walk_left",
      "walk_wing",
      "walk_wing_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "walk",
      "walk_left",
      "walk_wing",
      "walk_wing_left",
    },
    hover_still = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    hover_still_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    fly_derp = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    fly_derp_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    hover_derp = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    hover_derp_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    grab_mail = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly_mail_1",
    },
    grab_mail_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly_mail_1",
    },
    fly_mail_1 = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly_mail_2",
    },
    fly_mail_1_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly_mail_2",
    },
    fly_mail_2 = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly_mail_3",
    },
    fly_mail_2_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "fly_mail_3",
    },
    fly_mail_3 = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "putaway_mail",
    },
    fly_mail_3_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "putaway_mail",
    },
    putaway_mail = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    putaway_mail_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    muffin = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    muffin_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    sit = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    sit_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    drag = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    drag_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    cloud_start = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "cloud_bounce",
    },
    cloud_start_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
      "cloud_bounce",
    },
    cloud_bounce = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
    cloud_bounce_left = {
      "stand",
      "stand_left",
      "stand_wing",
      "stand_wing_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "stand_wing",
    "stand_wing_left",
    "sleep",
    "sleep_left",
    "walk_wing",
    "walk_wing_left",
    "hover_still",
    "hover_still_left",
    "fly_derp",
    "fly_derp_left",
    "hover_derp",
    "hover_derp_left",
    "grab_mail",
    "grab_mail_left",
    "fly_mail_1",
    "fly_mail_1_left",
    "fly_mail_2",
    "fly_mail_2_left",
    "fly_mail_3",
    "fly_mail_3_left",
    "putaway_mail",
    "putaway_mail_left",
    "muffin",
    "muffin_left",
    "sit",
    "sit_left",
    "drag",
    "drag_left",
    "cloud_start",
    "cloud_start_left",
    "cloud_bounce",
    "cloud_bounce_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
        "fly",
      },
      fast = {
        "walk",
        "fly",
      },
      slow = {
        "walk",
        "fly",
      },
    },
    left = {
      normal = {
        "walk_left",
        "fly_left",
      },
      fast = {
        "walk_left",
        "fly_left",
      },
      slow = {
        "walk_left",
        "fly_left",
      },
    },
  },
}