return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "dash",
      "dash_left",
      "walk",
      "walk_left",
      "glasses",
      "glasses_left",
      "bigmac-start",
      "bigmac-start_left",
      "bigmac-follow",
      "bigmac-follow_left",
      "bigmac-end",
      "bigmac-end_left",
      "get-dressed",
      "get-dressed_left",
      "uniform_stand",
      "uniform_stand_left",
      "uniform_fly",
      "uniform_fly_left",
      "uniform_dash",
      "uniform_dash_left",
      "uniform_walk",
      "uniform_walk_left",
      "undress",
      "undress_left",
      "wonderbolts_1",
      "wonderbolts_1_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "dash",
      "dash_left",
      "walk",
      "walk_left",
      "glasses",
      "glasses_left",
      "bigmac-start",
      "bigmac-start_left",
      "bigmac-follow",
      "bigmac-follow_left",
      "bigmac-end",
      "bigmac-end_left",
      "get-dressed",
      "get-dressed_left",
      "uniform_stand",
      "uniform_stand_left",
      "uniform_fly",
      "uniform_fly_left",
      "uniform_dash",
      "uniform_dash_left",
      "uniform_walk",
      "uniform_walk_left",
      "undress",
      "undress_left",
      "wonderbolts_1",
      "wonderbolts_1_left",
    },
    fly = {
      "stand",
      "stand_left",
    },
    fly_left = {
      "stand",
      "stand_left",
    },
    dash = {
      "stand",
      "stand_left",
    },
    dash_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    glasses = {
      "stand",
      "stand_left",
    },
    glasses_left = {
      "stand",
      "stand_left",
    },
    ["bigmac-start"] = {
      "stand",
      "stand_left",
      "bigmac-follow",
    },
    ["bigmac-start_left"] = {
      "stand",
      "stand_left",
      "bigmac-follow",
    },
    ["bigmac-follow"] = {
      "stand",
      "stand_left",
      "bigmac-end",
    },
    ["bigmac-follow_left"] = {
      "stand",
      "stand_left",
      "bigmac-end",
    },
    ["bigmac-end"] = {
      "stand",
      "stand_left",
    },
    ["bigmac-end_left"] = {
      "stand",
      "stand_left",
    },
    ["get-dressed"] = {
      "stand",
      "stand_left",
      "uniform_stand",
    },
    ["get-dressed_left"] = {
      "stand",
      "stand_left",
      "uniform_stand",
    },
    uniform_stand = {
      "stand",
      "stand_left",
    },
    uniform_stand_left = {
      "stand",
      "stand_left",
    },
    uniform_fly = {
      "stand",
      "stand_left",
    },
    uniform_fly_left = {
      "stand",
      "stand_left",
    },
    uniform_dash = {
      "stand",
      "stand_left",
    },
    uniform_dash_left = {
      "stand",
      "stand_left",
    },
    uniform_walk = {
      "stand",
      "stand_left",
    },
    uniform_walk_left = {
      "stand",
      "stand_left",
    },
    undress = {
      "stand",
      "stand_left",
    },
    undress_left = {
      "stand",
      "stand_left",
    },
    wonderbolts_1 = {
      "stand",
      "stand_left",
    },
    wonderbolts_1_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "dash",
    "dash_left",
    "glasses",
    "glasses_left",
    "bigmac-start",
    "bigmac-start_left",
    "bigmac-follow",
    "bigmac-follow_left",
    "bigmac-end",
    "bigmac-end_left",
    "get-dressed",
    "get-dressed_left",
    "uniform_stand",
    "uniform_stand_left",
    "uniform_fly",
    "uniform_fly_left",
    "uniform_dash",
    "uniform_dash_left",
    "uniform_walk",
    "uniform_walk_left",
    "undress",
    "undress_left",
    "wonderbolts_1",
    "wonderbolts_1_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
        "walk",
      },
      fast = {
        "fly",
        "walk",
      },
      slow = {
        "fly",
        "walk",
      },
    },
    left = {
      normal = {
        "fly_left",
        "walk_left",
      },
      fast = {
        "fly_left",
        "walk_left",
      },
      slow = {
        "fly_left",
        "walk_left",
      },
    },
  },
}