return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "fly_straight",
      "fly_straight_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
      "stare",
      "stare_left",
      "sleep",
      "sleep_left",
      "drag",
      "drag_left",
      "mouseover",
      "mouseover_left",
      "crystallized",
      "crystallized_left",
      "photo_shoot_start",
      "theme 1",
      "theme 1_left",
      "flottosho",
      "flottosho_left",
      "breezie",
      "breezie_left",
      "conga",
      "conga_left",
      "cuddles",
      "lift",
      "goto_galla",
      "goto_galla_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
      "trot_wings",
      "trot_wings_left",
      "theme 1 gala",
      "theme 1 gala_left",
      "critter",
      "critter_left",
      "critter_catch",
      "critter_catch_left",
      "fly_gala",
      "fly_gala_left",
      "flottosho gala",
      "flottosho gala_left",
      "gala_drag",
      "gala_drag_left",
      "leave_gala",
      "leave_gala_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "fly_straight",
      "fly_straight_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
      "stare",
      "stare_left",
      "sleep",
      "sleep_left",
      "drag",
      "drag_left",
      "mouseover",
      "mouseover_left",
      "crystallized",
      "crystallized_left",
      "photo_shoot_start",
      "theme 1",
      "theme 1_left",
      "flottosho",
      "flottosho_left",
      "breezie",
      "breezie_left",
      "conga",
      "conga_left",
      "cuddles",
      "lift",
      "goto_galla",
      "goto_galla_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
      "trot_wings",
      "trot_wings_left",
      "theme 1 gala",
      "theme 1 gala_left",
      "critter",
      "critter_left",
      "critter_catch",
      "critter_catch_left",
      "fly_gala",
      "fly_gala_left",
      "flottosho gala",
      "flottosho gala_left",
      "gala_drag",
      "gala_drag_left",
      "leave_gala",
      "leave_gala_left",
    },
    fly_straight = {
      "stand",
      "stand_left",
    },
    fly_straight_left = {
      "stand",
      "stand_left",
    },
    fly = {
      "stand",
      "stand_left",
    },
    fly_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
      "trot",
      "trot_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
      "trot",
      "trot_left",
    },
    stare = {
      "stand",
      "stand_left",
    },
    stare_left = {
      "stand",
      "stand_left",
    },
    sleep = {
      "stand",
      "stand_left",
    },
    sleep_left = {
      "stand",
      "stand_left",
    },
    drag = {
      "stand",
      "stand_left",
    },
    drag_left = {
      "stand",
      "stand_left",
    },
    mouseover = {
      "stand",
      "stand_left",
    },
    mouseover_left = {
      "stand",
      "stand_left",
    },
    gallop = {
      "walk",
      "walk_left",
      "trot",
      "trot_left",
    },
    gallop_left = {
      "walk",
      "walk_left",
      "trot",
      "trot_left",
    },
    crystallized = {
      "stand",
      "stand_left",
    },
    crystallized_left = {
      "stand",
      "stand_left",
    },
    photo_shoot_start = {
      "stand",
      "stand_left",
    },
    ["theme 1"] = {
      "stand",
      "stand_left",
    },
    ["theme 1_left"] = {
      "stand",
      "stand_left",
    },
    flottosho = {
      "stand",
      "stand_left",
    },
    flottosho_left = {
      "stand",
      "stand_left",
    },
    breezie = {
      "stand",
      "stand_left",
    },
    breezie_left = {
      "stand",
      "stand_left",
    },
    conga = {
      "stand",
      "stand_left",
    },
    conga_left = {
      "stand",
      "stand_left",
    },
    cuddles = {
      "stand",
      "stand_left",
    },
    lift = {
      "stand",
      "stand_left",
    },
    goto_galla = {
      "stand",
      "stand_left",
    },
    goto_galla_left = {
      "stand",
      "stand_left",
    },
    stand_left_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
      "trot_wings",
      "trot_wings_left",
      "theme 1 gala",
      "theme 1 gala_left",
      "critter",
      "critter_left",
      "critter_catch",
      "critter_catch_left",
      "fly_gala",
      "fly_gala_left",
      "flottosho gala",
      "flottosho gala_left",
      "gala_drag",
      "gala_drag_left",
      "leave_gala",
      "leave_gala_left",
    },
    stand_wings = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
      "trot_wings",
      "trot_wings_left",
      "theme 1 gala",
      "theme 1 gala_left",
      "critter",
      "critter_left",
      "critter_catch",
      "critter_catch_left",
      "fly_gala",
      "fly_gala_left",
      "flottosho gala",
      "flottosho gala_left",
      "gala_drag",
      "gala_drag_left",
      "leave_gala",
      "leave_gala_left",
    },
    stand_wings_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
      "trot_wings",
      "trot_wings_left",
      "theme 1 gala",
      "theme 1 gala_left",
      "critter",
      "critter_left",
      "critter_catch",
      "critter_catch_left",
      "fly_gala",
      "fly_gala_left",
      "flottosho gala",
      "flottosho gala_left",
      "gala_drag",
      "gala_drag_left",
      "leave_gala",
      "leave_gala_left",
    },
    trot = {
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
    },
    trot_left = {
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
    },
    trot_wings = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    trot_wings_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    ["theme 1 gala"] = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    ["theme 1 gala_left"] = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    critter = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    critter_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    critter_catch = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
      "critter",
    },
    critter_catch_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
      "critter",
    },
    fly_gala = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    fly_gala_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    ["flottosho gala"] = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    ["flottosho gala_left"] = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    gala_drag = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    gala_drag_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    leave_gala = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
    leave_gala_left = {
      "stand",
      "stand_left",
      "stand_left_left",
      "stand_wings",
      "stand_wings_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "fly_straight",
    "fly_straight_left",
    "stare",
    "stare_left",
    "sleep",
    "sleep_left",
    "drag",
    "drag_left",
    "mouseover",
    "mouseover_left",
    "crystallized",
    "crystallized_left",
    "photo_shoot_start",
    "theme 1",
    "theme 1_left",
    "flottosho",
    "flottosho_left",
    "breezie",
    "breezie_left",
    "conga",
    "conga_left",
    "cuddles",
    "lift",
    "goto_galla",
    "goto_galla_left",
    "stand_left_left",
    "stand_wings",
    "stand_wings_left",
    "trot_wings",
    "trot_wings_left",
    "theme 1 gala",
    "theme 1 gala_left",
    "critter",
    "critter_left",
    "critter_catch",
    "critter_catch_left",
    "fly_gala",
    "fly_gala_left",
    "flottosho gala",
    "flottosho gala_left",
    "gala_drag",
    "gala_drag_left",
    "leave_gala",
    "leave_gala_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
        "walk",
      },
      fast = {
        "gallop",
      },
      slow = {
        "fly",
        "walk",
      },
    },
    left = {
      normal = {
        "fly_left",
        "walk_left",
        "gallop_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {
        "fly_left",
        "walk_left",
      },
    },
  },
}