return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "lying",
      "lying_left",
      "boulder",
      "boulder_left",
      "poem 1",
      "poem 1_left",
      "poem 2",
      "poem 2_left",
      "poem 3",
      "poem 3_left",
      "poem 4",
      "poem 4_left",
      "poem 5",
      "poem 5_left",
      "poem 6",
      "poem 6_left",
      "poem 7",
      "poem 7_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "lying",
      "lying_left",
      "boulder",
      "boulder_left",
      "poem 1",
      "poem 1_left",
      "poem 2",
      "poem 2_left",
      "poem 3",
      "poem 3_left",
      "poem 4",
      "poem 4_left",
      "poem 5",
      "poem 5_left",
      "poem 6",
      "poem 6_left",
      "poem 7",
      "poem 7_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    lying = {
      "stand",
      "stand_left",
    },
    lying_left = {
      "stand",
      "stand_left",
    },
    boulder = {
      "stand",
      "stand_left",
    },
    boulder_left = {
      "stand",
      "stand_left",
    },
    ["poem 1"] = {
      "stand",
      "stand_left",
      "poem 2",
    },
    ["poem 1_left"] = {
      "stand",
      "stand_left",
      "poem 2",
    },
    ["poem 2"] = {
      "stand",
      "stand_left",
      "poem 3",
    },
    ["poem 2_left"] = {
      "stand",
      "stand_left",
      "poem 3",
    },
    ["poem 3"] = {
      "stand",
      "stand_left",
      "poem 4",
    },
    ["poem 3_left"] = {
      "stand",
      "stand_left",
      "poem 4",
    },
    ["poem 4"] = {
      "stand",
      "stand_left",
      "poem 5",
    },
    ["poem 4_left"] = {
      "stand",
      "stand_left",
      "poem 5",
    },
    ["poem 5"] = {
      "stand",
      "stand_left",
      "poem 6",
    },
    ["poem 5_left"] = {
      "stand",
      "stand_left",
      "poem 6",
    },
    ["poem 6"] = {
      "stand",
      "stand_left",
      "poem 7",
    },
    ["poem 6_left"] = {
      "stand",
      "stand_left",
      "poem 7",
    },
    ["poem 7"] = {
      "stand",
      "stand_left",
    },
    ["poem 7_left"] = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "lying",
    "lying_left",
    "boulder",
    "boulder_left",
    "poem 1",
    "poem 1_left",
    "poem 2",
    "poem 2_left",
    "poem 3",
    "poem 3_left",
    "poem 4",
    "poem 4_left",
    "poem 5",
    "poem 5_left",
    "poem 6",
    "poem 6_left",
    "poem 7",
    "poem 7_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "walk",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "walk_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}