return {
  next_actions = {
    start_purple = {
      "purple-fly",
    },
    start_blue = {
      "blue-fly",
    },
    start_brown = {
      "brown-fly",
    },
    start_orange = {
      "orange-fly",
    },
    start_pink = {
      "pink-fly",
    },
    start_yellow = {
      "yellow-fly",
    },
    start_red = {
      "red-fly",
    },
    start_green = {
      "green-fly",
    },
    ["blue-stand"] = {},
    ["blue-fly"] = {},
    ["blue-fly_left"] = {},
    ["blue-updown"] = {},
    ["brown-stand"] = {},
    ["brown-fly"] = {},
    ["brown-fly_left"] = {},
    ["brown-updown"] = {},
    ["orange-stand"] = {},
    ["orange-fly"] = {},
    ["orange-fly_left"] = {},
    ["orange-updown"] = {},
    ["pink-stand"] = {},
    ["pink-fly"] = {},
    ["pink-fly_left"] = {},
    ["pink-updown"] = {},
    ["purple-stand"] = {},
    ["purple-fly"] = {},
    ["purple-fly_left"] = {},
    ["purple-updown"] = {},
    ["yellow-stand"] = {},
    ["yellow-fly"] = {},
    ["yellow-fly_left"] = {},
    ["yellow-updown"] = {},
    ["red-stand"] = {},
    ["red-fly"] = {},
    ["red-fly_left"] = {},
    ["red-updown"] = {},
    ["green-stand"] = {},
    ["green-fly"] = {},
    ["green-fly_left"] = {},
    ["green-updown"] = {},
  },
  idle_actions = {
    "start_purple",
    "start_blue",
    "start_brown",
    "start_orange",
    "start_pink",
    "start_yellow",
    "start_red",
    "start_green",
    "blue-stand",
    "blue-fly",
    "blue-fly_left",
    "blue-updown",
    "brown-stand",
    "brown-fly",
    "brown-fly_left",
    "brown-updown",
    "orange-stand",
    "orange-fly",
    "orange-fly_left",
    "orange-updown",
    "pink-stand",
    "pink-fly",
    "pink-fly_left",
    "pink-updown",
    "purple-stand",
    "purple-fly",
    "purple-fly_left",
    "purple-updown",
    "yellow-stand",
    "yellow-fly",
    "yellow-fly_left",
    "yellow-updown",
    "red-stand",
    "red-fly",
    "red-fly_left",
    "red-updown",
    "green-stand",
    "green-fly",
    "green-fly_left",
    "green-updown",
  },
  first_action = "start_purple",
  movements = {
    right = {
      normal = {},
      fast = {},
      slow = {},
    },
    left = {
      normal = {},
      fast = {},
      slow = {},
    },
  },
}