return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "walk_n_n",
      "walk_n_n_left",
      "parade",
      "parade_left",
      "bounce",
      "bounce_left",
      "bounce_n_n",
      "bounce_n_n_left",
      "bounce_up",
      "bounce_up_left",
      "parasprite_follow_circle1",
      "parasprite_follow_circle1_left",
      "parasprite_follow_circle2",
      "parasprite_follow_circle2_left",
      "parasprite_follow_circle3",
      "parasprite_follow_circle3_left",
      "parasprite_follow_circle4",
      "parasprite_follow_circle4_left",
      "parasprite_follow_circle5",
      "parasprite_follow_circle5_left",
      "theme 1",
      "theme 1_left",
      "pinkie_balloon_poke",
      "pinkie_balloon_poke_left",
      "stalking_start",
      "stalking_start_left",
      "stalking_dash",
      "stalking_dash_left",
      "stalking_stop",
      "stalking_stop_left",
      "wink",
      "wink_left",
      "drag",
      "drag_left",
      "mouseover",
      "mouseover_left",
      "hatersgonnahate",
      "hatersgonnahate_left",
      "haterstart",
      "haterstart_left",
      "giggle",
      "giggle_left",
      "jumpturn",
      "jumpturn_left",
      "jumpturnpl",
      "jumpturnpl_left",
      "flower1",
      "flower1_left",
      "walk2",
      "walk2_left",
      "jumpy",
      "jumpy_left",
      "rollfinish",
      "rollfinish_left",
      "rollend",
      "rollend_left",
      "rollsequence",
      "rollsequence_left",
      "rollstart",
      "rollstart_left",
      "rolljump",
      "rolljump_left",
      "rollfinish2",
      "rollfinish2_left",
      "rollend2",
      "rollend2_left",
      "rollsequence2",
      "rollsequence2_left",
      "rollstart2",
      "rollstart2_left",
      "rolljump2",
      "rolljump2_left",
      "rolltransition",
      "rolltransition_left",
      "hick1",
      "hick1_left",
      "hick2mix",
      "hick2mix_left",
      "rofl",
      "rofl_left",
      "hick3",
      "hick3_left",
      "jumpflower",
      "jumpflower_left",
      "jumppreflowe",
      "jumppreflowe_left",
      "flower2",
      "flower2_left",
      "flower3",
      "flower3_left",
      "tongue",
      "tongue_left",
      "flower6",
      "flower6_left",
      "flower5",
      "flower5_left",
      "flower4mix",
      "flower4mix_left",
      "flower7",
      "flower7_left",
      "jumpflower2",
      "jumpflower2_left",
      "jumppreflowe2",
      "jumppreflowe2_left",
      "jumpflower3",
      "jumpflower3_left",
      "jumppreflowe3",
      "jumppreflowe3_left",
      "cupcake",
      "cupcake_left",
      "chicken",
      "chicken_left",
      "sleep",
      "sleep_left",
      "rest",
      "rest_left",
      "pinkacopter",
      "pinkacopter_left",
      "pinkacopter2",
      "pinkacopter2_left",
      "pinkacopter3",
      "pinkacopter3_left",
      "pinkacopter4",
      "pinkacopter4_left",
      "pinkacopter5",
      "pinkacopter5_left",
      "pinkacopter_start",
      "pinkacopter_start_left",
      "pinkacopter_begin",
      "pinkacopter_begin_left",
      "pinkacopter_stop",
      "pinkacopter_stop_left",
      "backtrack",
      "backtrack_left",
      "parasprite_stop",
      "parasprite_stop_left",
      "parade_start",
      "parade_start_left",
      "parasprite_follow_circle",
      "parasprite_follow_circle_left",
      "dance_tongue",
      "dance_tongue_left",
      "haters_stop",
      "haters_stop_left",
      "princess",
      "princess_left",
      "cartwheel",
      "cartwheel_left",
      "sittinggiggle",
      "sittinggiggle_left",
      "sneeze_stop",
      "sneeze_stop_left",
      "sneeze_fly",
      "sneeze_fly_left",
      "sneeze_start",
      "sneeze_start_left",
      "sneeze_cute",
      "sneeze_cute_left",
      "parasoloff",
      "parasoloff_left",
      "twitchyrun",
      "twitchyrun_left",
      "parasolon",
      "parasolon_left",
      "twitchytail",
      "twitchytail_left",
      "parasolon2",
      "parasolon2_left",
      "twitchytail2",
      "twitchytail2_left",
      "bite_left",
      "bite_right",
      "pose",
      "pose_left",
      "hickup_start_1",
      "hickup_start_1_left",
      "hickup_start_1-2",
      "hickup_start_1-2_left",
      "hickup_start_2",
      "hickup_start_2_left",
      "hickup_start_2-2",
      "hickup_start_2-2_left",
      "hickup_start_3",
      "hickup_start_3_left",
      "hickup_start_3-2",
      "hickup_start_3-2_left",
      "hickup_start_4",
      "hickup_start_4_left",
      "hickup_start_4-2",
      "hickup_start_4-2_left",
      "hickup_stop",
      "hickup_stop_left",
      "sitrofl",
      "sitrofl_left",
      "rofls2stop",
      "rofls2stop_left",
      "rofls2",
      "rofls2_left",
      "rofls2start",
      "rofls2start_left",
      "crocodance",
      "crocodance_left",
      "teleportreappear",
      "teleportreappear_left",
      "teleport run",
      "pinkaport",
      "pinkaport_left",
      "cannonshoot",
      "cannonshoot_left",
      "cannonrun",
      "cannonrun_left",
      "cannostart",
      "cannostart_left",
      "cannonfull",
      "cannonfull_left",
      "ponko poe",
      "ponko poe_left",
      "oink-end",
      "oink-end_left",
      "oinkbutt",
      "oinkbutt_left",
      "oinktail",
      "oinktail_left",
      "oinkstart",
      "oinkstart_left",
      "salto_end",
      "salto_end_left",
      "salto",
      "salto_left",
      "salto_start",
      "salto_start_left",
      "salto2",
      "salto2_left",
      "salto_start2",
      "salto_start2_left",
      "flip_end",
      "flip_end_left",
      "flip",
      "flip_left",
      "flip_start",
      "flip_start_left",
      "oinkprestart",
      "oinkprestart_left",
      "sit",
      "sit_left",
      "epic rearing",
      "epic rearing_left",
      "epic rearing2",
      "epic rearing2_left",
      "canoncake",
      "canoncake_left",
      "canoncake2",
      "canoncake2_left",
      "galopp",
      "galopp_left",
      "conga start",
      "conga start_left",
      "conga",
      "conga_left",
      "chicken2",
      "chicken2_left",
      "fluttercuddle_left",
      "fluttercuddle_right",
      "crystallized",
      "crystallized_left",
      "goto_gala",
      "goto_gala_left",
      "gala_stand",
      "gala_stand_left",
      "gala_trot",
      "gala_trot_left",
      "gala_trot n_n",
      "gala_trot n_n_left",
      "gala_bounce",
      "gala_bounce_left",
      "gala_bounce n_n",
      "gala_bounce n_n_left",
      "gala_drag",
      "gala_drag_left",
      "ponko poe gala",
      "ponko poe gala_left",
      "theme 1 gala",
      "theme 1 gala_left",
      "leave_gala",
      "leave_gala_left",
      "breezie",
      "breezie_left",
      "sleep1",
      "sleep1_left",
      "weddingdance_start",
      "weddingdance_start_left",
      "weddingdance",
      "weddingdance_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "walk_n_n",
      "walk_n_n_left",
      "parade",
      "parade_left",
      "bounce",
      "bounce_left",
      "bounce_n_n",
      "bounce_n_n_left",
      "bounce_up",
      "bounce_up_left",
      "parasprite_follow_circle1",
      "parasprite_follow_circle1_left",
      "parasprite_follow_circle2",
      "parasprite_follow_circle2_left",
      "parasprite_follow_circle3",
      "parasprite_follow_circle3_left",
      "parasprite_follow_circle4",
      "parasprite_follow_circle4_left",
      "parasprite_follow_circle5",
      "parasprite_follow_circle5_left",
      "theme 1",
      "theme 1_left",
      "pinkie_balloon_poke",
      "pinkie_balloon_poke_left",
      "stalking_start",
      "stalking_start_left",
      "stalking_dash",
      "stalking_dash_left",
      "stalking_stop",
      "stalking_stop_left",
      "wink",
      "wink_left",
      "drag",
      "drag_left",
      "mouseover",
      "mouseover_left",
      "hatersgonnahate",
      "hatersgonnahate_left",
      "haterstart",
      "haterstart_left",
      "giggle",
      "giggle_left",
      "jumpturn",
      "jumpturn_left",
      "jumpturnpl",
      "jumpturnpl_left",
      "flower1",
      "flower1_left",
      "walk2",
      "walk2_left",
      "jumpy",
      "jumpy_left",
      "rollfinish",
      "rollfinish_left",
      "rollend",
      "rollend_left",
      "rollsequence",
      "rollsequence_left",
      "rollstart",
      "rollstart_left",
      "rolljump",
      "rolljump_left",
      "rollfinish2",
      "rollfinish2_left",
      "rollend2",
      "rollend2_left",
      "rollsequence2",
      "rollsequence2_left",
      "rollstart2",
      "rollstart2_left",
      "rolljump2",
      "rolljump2_left",
      "rolltransition",
      "rolltransition_left",
      "hick1",
      "hick1_left",
      "hick2mix",
      "hick2mix_left",
      "rofl",
      "rofl_left",
      "hick3",
      "hick3_left",
      "jumpflower",
      "jumpflower_left",
      "jumppreflowe",
      "jumppreflowe_left",
      "flower2",
      "flower2_left",
      "flower3",
      "flower3_left",
      "tongue",
      "tongue_left",
      "flower6",
      "flower6_left",
      "flower5",
      "flower5_left",
      "flower4mix",
      "flower4mix_left",
      "flower7",
      "flower7_left",
      "jumpflower2",
      "jumpflower2_left",
      "jumppreflowe2",
      "jumppreflowe2_left",
      "jumpflower3",
      "jumpflower3_left",
      "jumppreflowe3",
      "jumppreflowe3_left",
      "cupcake",
      "cupcake_left",
      "chicken",
      "chicken_left",
      "sleep",
      "sleep_left",
      "rest",
      "rest_left",
      "pinkacopter",
      "pinkacopter_left",
      "pinkacopter2",
      "pinkacopter2_left",
      "pinkacopter3",
      "pinkacopter3_left",
      "pinkacopter4",
      "pinkacopter4_left",
      "pinkacopter5",
      "pinkacopter5_left",
      "pinkacopter_start",
      "pinkacopter_start_left",
      "pinkacopter_begin",
      "pinkacopter_begin_left",
      "pinkacopter_stop",
      "pinkacopter_stop_left",
      "backtrack",
      "backtrack_left",
      "parasprite_stop",
      "parasprite_stop_left",
      "parade_start",
      "parade_start_left",
      "parasprite_follow_circle",
      "parasprite_follow_circle_left",
      "dance_tongue",
      "dance_tongue_left",
      "haters_stop",
      "haters_stop_left",
      "princess",
      "princess_left",
      "cartwheel",
      "cartwheel_left",
      "sittinggiggle",
      "sittinggiggle_left",
      "sneeze_stop",
      "sneeze_stop_left",
      "sneeze_fly",
      "sneeze_fly_left",
      "sneeze_start",
      "sneeze_start_left",
      "sneeze_cute",
      "sneeze_cute_left",
      "parasoloff",
      "parasoloff_left",
      "twitchyrun",
      "twitchyrun_left",
      "parasolon",
      "parasolon_left",
      "twitchytail",
      "twitchytail_left",
      "parasolon2",
      "parasolon2_left",
      "twitchytail2",
      "twitchytail2_left",
      "bite_left",
      "bite_right",
      "pose",
      "pose_left",
      "hickup_start_1",
      "hickup_start_1_left",
      "hickup_start_1-2",
      "hickup_start_1-2_left",
      "hickup_start_2",
      "hickup_start_2_left",
      "hickup_start_2-2",
      "hickup_start_2-2_left",
      "hickup_start_3",
      "hickup_start_3_left",
      "hickup_start_3-2",
      "hickup_start_3-2_left",
      "hickup_start_4",
      "hickup_start_4_left",
      "hickup_start_4-2",
      "hickup_start_4-2_left",
      "hickup_stop",
      "hickup_stop_left",
      "sitrofl",
      "sitrofl_left",
      "rofls2stop",
      "rofls2stop_left",
      "rofls2",
      "rofls2_left",
      "rofls2start",
      "rofls2start_left",
      "crocodance",
      "crocodance_left",
      "teleportreappear",
      "teleportreappear_left",
      "teleport run",
      "pinkaport",
      "pinkaport_left",
      "cannonshoot",
      "cannonshoot_left",
      "cannonrun",
      "cannonrun_left",
      "cannostart",
      "cannostart_left",
      "cannonfull",
      "cannonfull_left",
      "ponko poe",
      "ponko poe_left",
      "oink-end",
      "oink-end_left",
      "oinkbutt",
      "oinkbutt_left",
      "oinktail",
      "oinktail_left",
      "oinkstart",
      "oinkstart_left",
      "salto_end",
      "salto_end_left",
      "salto",
      "salto_left",
      "salto_start",
      "salto_start_left",
      "salto2",
      "salto2_left",
      "salto_start2",
      "salto_start2_left",
      "flip_end",
      "flip_end_left",
      "flip",
      "flip_left",
      "flip_start",
      "flip_start_left",
      "oinkprestart",
      "oinkprestart_left",
      "sit",
      "sit_left",
      "epic rearing",
      "epic rearing_left",
      "epic rearing2",
      "epic rearing2_left",
      "canoncake",
      "canoncake_left",
      "canoncake2",
      "canoncake2_left",
      "galopp",
      "galopp_left",
      "conga start",
      "conga start_left",
      "conga",
      "conga_left",
      "chicken2",
      "chicken2_left",
      "fluttercuddle_left",
      "fluttercuddle_right",
      "crystallized",
      "crystallized_left",
      "goto_gala",
      "goto_gala_left",
      "gala_stand",
      "gala_stand_left",
      "gala_trot",
      "gala_trot_left",
      "gala_trot n_n",
      "gala_trot n_n_left",
      "gala_bounce",
      "gala_bounce_left",
      "gala_bounce n_n",
      "gala_bounce n_n_left",
      "gala_drag",
      "gala_drag_left",
      "ponko poe gala",
      "ponko poe gala_left",
      "theme 1 gala",
      "theme 1 gala_left",
      "leave_gala",
      "leave_gala_left",
      "breezie",
      "breezie_left",
      "sleep1",
      "sleep1_left",
      "weddingdance_start",
      "weddingdance_start_left",
      "weddingdance",
      "weddingdance_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_n_n = {
      "stand",
      "stand_left",
    },
    walk_n_n_left = {
      "stand",
      "stand_left",
    },
    parade = {
      "stand",
      "stand_left",
      "parasprite_stop",
    },
    parade_left = {
      "stand",
      "stand_left",
      "parasprite_stop",
    },
    bounce = {
      "stand",
      "stand_left",
    },
    bounce_left = {
      "stand",
      "stand_left",
    },
    bounce_n_n = {
      "stand",
      "stand_left",
    },
    bounce_n_n_left = {
      "stand",
      "stand_left",
    },
    bounce_up = {
      "stand",
      "stand_left",
    },
    bounce_up_left = {
      "stand",
      "stand_left",
    },
    parasprite_follow_circle1 = {
      "stand",
      "stand_left",
      "parasprite_follow_circle2",
    },
    parasprite_follow_circle1_left = {
      "stand",
      "stand_left",
      "parasprite_follow_circle2",
    },
    parasprite_follow_circle2 = {
      "stand",
      "stand_left",
      "parasprite_follow_circle3",
    },
    parasprite_follow_circle2_left = {
      "stand",
      "stand_left",
      "parasprite_follow_circle3",
    },
    parasprite_follow_circle3 = {
      "stand",
      "stand_left",
      "parasprite_follow_circle4",
    },
    parasprite_follow_circle3_left = {
      "stand",
      "stand_left",
      "parasprite_follow_circle4",
    },
    parasprite_follow_circle4 = {
      "stand",
      "stand_left",
      "parasprite_follow_circle5",
    },
    parasprite_follow_circle4_left = {
      "stand",
      "stand_left",
      "parasprite_follow_circle5",
    },
    parasprite_follow_circle5 = {
      "stand",
      "stand_left",
      "parasprite_stop",
    },
    parasprite_follow_circle5_left = {
      "stand",
      "stand_left",
      "parasprite_stop",
    },
    ["theme 1"] = {
      "stand",
      "stand_left",
    },
    ["theme 1_left"] = {
      "stand",
      "stand_left",
    },
    pinkie_balloon_poke = {
      "stand",
      "stand_left",
    },
    pinkie_balloon_poke_left = {
      "stand",
      "stand_left",
    },
    stalking_start = {
      "stand",
      "stand_left",
      "Stalking_Dash",
    },
    stalking_start_left = {
      "stand",
      "stand_left",
      "Stalking_Dash",
    },
    stalking_dash = {
      "stand",
      "stand_left",
      "Stalking_stop",
    },
    stalking_dash_left = {
      "stand",
      "stand_left",
      "Stalking_stop",
    },
    stalking_stop = {
      "stand",
      "stand_left",
    },
    stalking_stop_left = {
      "stand",
      "stand_left",
    },
    wink = {
      "stand",
      "stand_left",
    },
    wink_left = {
      "stand",
      "stand_left",
    },
    drag = {
      "stand",
      "stand_left",
    },
    drag_left = {
      "stand",
      "stand_left",
    },
    mouseover = {
      "stand",
      "stand_left",
    },
    mouseover_left = {
      "stand",
      "stand_left",
    },
    hatersgonnahate = {
      "stand",
      "stand_left",
      "haters_stop",
    },
    hatersgonnahate_left = {
      "stand",
      "stand_left",
      "haters_stop",
    },
    haterstart = {
      "stand",
      "stand_left",
      "hatersgonnahate",
    },
    haterstart_left = {
      "stand",
      "stand_left",
      "hatersgonnahate",
    },
    giggle = {
      "stand",
      "stand_left",
    },
    giggle_left = {
      "stand",
      "stand_left",
    },
    jumpturn = {
      "stand",
      "stand_left",
    },
    jumpturn_left = {
      "stand",
      "stand_left",
    },
    jumpturnpl = {
      "stand",
      "stand_left",
    },
    jumpturnpl_left = {
      "stand",
      "stand_left",
    },
    flower1 = {
      "stand",
      "stand_left",
    },
    flower1_left = {
      "stand",
      "stand_left",
    },
    walk2 = {
      "stand",
      "stand_left",
    },
    walk2_left = {
      "stand",
      "stand_left",
    },
    jumpy = {
      "stand",
      "stand_left",
    },
    jumpy_left = {
      "stand",
      "stand_left",
    },
    rollfinish = {
      "stand",
      "stand_left",
      "rolltransition",
    },
    rollfinish_left = {
      "stand",
      "stand_left",
      "rolltransition",
    },
    rollend = {
      "stand",
      "stand_left",
      "rollfinish",
    },
    rollend_left = {
      "stand",
      "stand_left",
      "rollfinish",
    },
    rollsequence = {
      "stand",
      "stand_left",
      "rollend",
    },
    rollsequence_left = {
      "stand",
      "stand_left",
      "rollend",
    },
    rollstart = {
      "stand",
      "stand_left",
      "rollsequence",
    },
    rollstart_left = {
      "stand",
      "stand_left",
      "rollsequence",
    },
    rolljump = {
      "stand",
      "stand_left",
      "rollstart",
    },
    rolljump_left = {
      "stand",
      "stand_left",
      "rollstart",
    },
    rollfinish2 = {
      "stand",
      "stand_left",
      "rolltransition",
    },
    rollfinish2_left = {
      "stand",
      "stand_left",
      "rolltransition",
    },
    rollend2 = {
      "stand",
      "stand_left",
      "rollfinish2",
    },
    rollend2_left = {
      "stand",
      "stand_left",
      "rollfinish2",
    },
    rollsequence2 = {
      "stand",
      "stand_left",
      "rollend2",
    },
    rollsequence2_left = {
      "stand",
      "stand_left",
      "rollend2",
    },
    rollstart2 = {
      "stand",
      "stand_left",
      "rollsequence2",
    },
    rollstart2_left = {
      "stand",
      "stand_left",
      "rollsequence2",
    },
    rolljump2 = {
      "stand",
      "stand_left",
      "rollstart2",
    },
    rolljump2_left = {
      "stand",
      "stand_left",
      "rollstart2",
    },
    rolltransition = {
      "stand",
      "stand_left",
    },
    rolltransition_left = {
      "stand",
      "stand_left",
    },
    hick1 = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    hick1_left = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    hick2mix = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    hick2mix_left = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    rofl = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    rofl_left = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    hick3 = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    hick3_left = {
      "stand",
      "stand_left",
      "hickup_stop",
    },
    jumpflower = {
      "stand",
      "stand_left",
      "jumppreflowe",
    },
    jumpflower_left = {
      "stand",
      "stand_left",
      "jumppreflowe",
    },
    jumppreflowe = {
      "stand",
      "stand_left",
      "flower2",
    },
    jumppreflowe_left = {
      "stand",
      "stand_left",
      "flower2",
    },
    flower2 = {
      "stand",
      "stand_left",
      "bounce_n_n",
    },
    flower2_left = {
      "stand",
      "stand_left",
      "bounce_n_n",
    },
    flower3 = {
      "stand",
      "stand_left",
    },
    flower3_left = {
      "stand",
      "stand_left",
    },
    tongue = {
      "stand",
      "stand_left",
    },
    tongue_left = {
      "stand",
      "stand_left",
    },
    flower6 = {
      "stand",
      "stand_left",
    },
    flower6_left = {
      "stand",
      "stand_left",
    },
    flower5 = {
      "stand",
      "stand_left",
    },
    flower5_left = {
      "stand",
      "stand_left",
    },
    flower4mix = {
      "stand",
      "stand_left",
      "bounce",
    },
    flower4mix_left = {
      "stand",
      "stand_left",
      "bounce",
    },
    flower7 = {
      "stand",
      "stand_left",
      "bounce",
    },
    flower7_left = {
      "stand",
      "stand_left",
      "bounce",
    },
    jumpflower2 = {
      "stand",
      "stand_left",
      "jumppreflowe2",
    },
    jumpflower2_left = {
      "stand",
      "stand_left",
      "jumppreflowe2",
    },
    jumppreflowe2 = {
      "stand",
      "stand_left",
      "flower7",
    },
    jumppreflowe2_left = {
      "stand",
      "stand_left",
      "flower7",
    },
    jumpflower3 = {
      "stand",
      "stand_left",
      "jumppreflowe3",
    },
    jumpflower3_left = {
      "stand",
      "stand_left",
      "jumppreflowe3",
    },
    jumppreflowe3 = {
      "stand",
      "stand_left",
      "flower4mix",
    },
    jumppreflowe3_left = {
      "stand",
      "stand_left",
      "flower4mix",
    },
    cupcake = {
      "stand",
      "stand_left",
    },
    cupcake_left = {
      "stand",
      "stand_left",
    },
    chicken = {
      "stand",
      "stand_left",
    },
    chicken_left = {
      "stand",
      "stand_left",
    },
    sleep = {
      "stand",
      "stand_left",
    },
    sleep_left = {
      "stand",
      "stand_left",
    },
    rest = {
      "stand",
      "stand_left",
    },
    rest_left = {
      "stand",
      "stand_left",
    },
    pinkacopter = {
      "stand",
      "stand_left",
      "Pinkacopter2",
    },
    pinkacopter_left = {
      "stand",
      "stand_left",
      "Pinkacopter2",
    },
    pinkacopter2 = {
      "stand",
      "stand_left",
      "Pinkacopter3",
    },
    pinkacopter2_left = {
      "stand",
      "stand_left",
      "Pinkacopter3",
    },
    pinkacopter3 = {
      "stand",
      "stand_left",
      "Pinkacopter4",
    },
    pinkacopter3_left = {
      "stand",
      "stand_left",
      "Pinkacopter4",
    },
    pinkacopter4 = {
      "stand",
      "stand_left",
      "Pinkacopter5",
    },
    pinkacopter4_left = {
      "stand",
      "stand_left",
      "Pinkacopter5",
    },
    pinkacopter5 = {
      "stand",
      "stand_left",
      "Pinkacopter_stop",
    },
    pinkacopter5_left = {
      "stand",
      "stand_left",
      "Pinkacopter_stop",
    },
    pinkacopter_start = {
      "stand",
      "stand_left",
      "Pinkacopter",
    },
    pinkacopter_start_left = {
      "stand",
      "stand_left",
      "Pinkacopter",
    },
    pinkacopter_begin = {
      "stand",
      "stand_left",
      "Pinkacopter",
    },
    pinkacopter_begin_left = {
      "stand",
      "stand_left",
      "Pinkacopter",
    },
    pinkacopter_stop = {
      "stand",
      "stand_left",
    },
    pinkacopter_stop_left = {
      "stand",
      "stand_left",
    },
    backtrack = {
      "stand",
      "stand_left",
    },
    backtrack_left = {
      "stand",
      "stand_left",
    },
    parasprite_stop = {
      "stand",
      "stand_left",
    },
    parasprite_stop_left = {
      "stand",
      "stand_left",
    },
    parade_start = {
      "stand",
      "stand_left",
      "parade",
    },
    parade_start_left = {
      "stand",
      "stand_left",
      "parade",
    },
    parasprite_follow_circle = {
      "stand",
      "stand_left",
      "parasprite_follow_circle1",
    },
    parasprite_follow_circle_left = {
      "stand",
      "stand_left",
      "parasprite_follow_circle1",
    },
    dance_tongue = {
      "stand",
      "stand_left",
    },
    dance_tongue_left = {
      "stand",
      "stand_left",
    },
    haters_stop = {
      "stand",
      "stand_left",
    },
    haters_stop_left = {
      "stand",
      "stand_left",
    },
    princess = {
      "stand",
      "stand_left",
    },
    princess_left = {
      "stand",
      "stand_left",
    },
    cartwheel = {
      "stand",
      "stand_left",
    },
    cartwheel_left = {
      "stand",
      "stand_left",
    },
    sittinggiggle = {
      "stand",
      "stand_left",
    },
    sittinggiggle_left = {
      "stand",
      "stand_left",
    },
    sneeze_stop = {
      "stand",
      "stand_left",
    },
    sneeze_stop_left = {
      "stand",
      "stand_left",
    },
    sneeze_fly = {
      "stand",
      "stand_left",
      "sneeze_stop",
    },
    sneeze_fly_left = {
      "stand",
      "stand_left",
      "sneeze_stop",
    },
    sneeze_start = {
      "stand",
      "stand_left",
      "sneeze_fly",
    },
    sneeze_start_left = {
      "stand",
      "stand_left",
      "sneeze_fly",
    },
    sneeze_cute = {
      "stand",
      "stand_left",
    },
    sneeze_cute_left = {
      "stand",
      "stand_left",
    },
    parasoloff = {
      "stand",
      "stand_left",
    },
    parasoloff_left = {
      "stand",
      "stand_left",
    },
    twitchyrun = {
      "stand",
      "stand_left",
      "parasoloff",
    },
    twitchyrun_left = {
      "stand",
      "stand_left",
      "parasoloff",
    },
    parasolon = {
      "stand",
      "stand_left",
      "twitchyrun",
    },
    parasolon_left = {
      "stand",
      "stand_left",
      "twitchyrun",
    },
    twitchytail = {
      "stand",
      "stand_left",
      "parasolon",
    },
    twitchytail_left = {
      "stand",
      "stand_left",
      "parasolon",
    },
    parasolon2 = {
      "stand",
      "stand_left",
      "twitchyrun",
    },
    parasolon2_left = {
      "stand",
      "stand_left",
      "twitchyrun",
    },
    twitchytail2 = {
      "stand",
      "stand_left",
      "parasolon2",
    },
    twitchytail2_left = {
      "stand",
      "stand_left",
      "parasolon2",
    },
    bite_left = {
      "stand",
      "stand_left",
    },
    bite_right = {
      "stand",
      "stand_left",
    },
    pose = {
      "stand",
      "stand_left",
    },
    pose_left = {
      "stand",
      "stand_left",
    },
    hickup_start_1 = {
      "stand",
      "stand_left",
      "hick1",
    },
    hickup_start_1_left = {
      "stand",
      "stand_left",
      "hick1",
    },
    ["hickup_start_1-2"] = {
      "stand",
      "stand_left",
      "hick1",
    },
    ["hickup_start_1-2_left"] = {
      "stand",
      "stand_left",
      "hick1",
    },
    hickup_start_2 = {
      "stand",
      "stand_left",
      "hick2mix",
    },
    hickup_start_2_left = {
      "stand",
      "stand_left",
      "hick2mix",
    },
    ["hickup_start_2-2"] = {
      "stand",
      "stand_left",
      "hick2mix",
    },
    ["hickup_start_2-2_left"] = {
      "stand",
      "stand_left",
      "hick2mix",
    },
    hickup_start_3 = {
      "stand",
      "stand_left",
      "rofl",
    },
    hickup_start_3_left = {
      "stand",
      "stand_left",
      "rofl",
    },
    ["hickup_start_3-2"] = {
      "stand",
      "stand_left",
      "rofl",
    },
    ["hickup_start_3-2_left"] = {
      "stand",
      "stand_left",
      "rofl",
    },
    hickup_start_4 = {
      "stand",
      "stand_left",
      "hick3",
    },
    hickup_start_4_left = {
      "stand",
      "stand_left",
      "hick3",
    },
    ["hickup_start_4-2"] = {
      "stand",
      "stand_left",
      "hick3",
    },
    ["hickup_start_4-2_left"] = {
      "stand",
      "stand_left",
      "hick3",
    },
    hickup_stop = {
      "stand",
      "stand_left",
    },
    hickup_stop_left = {
      "stand",
      "stand_left",
    },
    sitrofl = {
      "stand",
      "stand_left",
    },
    sitrofl_left = {
      "stand",
      "stand_left",
    },
    rofls2stop = {
      "stand",
      "stand_left",
    },
    rofls2stop_left = {
      "stand",
      "stand_left",
    },
    rofls2 = {
      "stand",
      "stand_left",
      "rofls2stop",
    },
    rofls2_left = {
      "stand",
      "stand_left",
      "rofls2stop",
    },
    rofls2start = {
      "stand",
      "stand_left",
      "rofls2",
    },
    rofls2start_left = {
      "stand",
      "stand_left",
      "rofls2",
    },
    crocodance = {
      "stand",
      "stand_left",
    },
    crocodance_left = {
      "stand",
      "stand_left",
    },
    teleportreappear = {
      "stand",
      "stand_left",
    },
    teleportreappear_left = {
      "stand",
      "stand_left",
    },
    ["teleport run"] = {
      "stand",
      "stand_left",
      "teleportreappear",
    },
    pinkaport = {
      "stand",
      "stand_left",
      "teleport run",
    },
    pinkaport_left = {
      "stand",
      "stand_left",
      "teleport run",
    },
    cannonshoot = {
      "stand",
      "stand_left",
    },
    cannonshoot_left = {
      "stand",
      "stand_left",
    },
    cannonrun = {
      "stand",
      "stand_left",
      "cannonshoot",
    },
    cannonrun_left = {
      "stand",
      "stand_left",
      "cannonshoot",
    },
    cannostart = {
      "stand",
      "stand_left",
      "cannonrun",
    },
    cannostart_left = {
      "stand",
      "stand_left",
      "cannonrun",
    },
    cannonfull = {
      "stand",
      "stand_left",
    },
    cannonfull_left = {
      "stand",
      "stand_left",
    },
    ["ponko poe"] = {
      "stand",
      "stand_left",
    },
    ["ponko poe_left"] = {
      "stand",
      "stand_left",
    },
    ["oink-end"] = {
      "stand",
      "stand_left",
    },
    ["oink-end_left"] = {
      "stand",
      "stand_left",
    },
    oinkbutt = {
      "stand",
      "stand_left",
      "oink-end",
    },
    oinkbutt_left = {
      "stand",
      "stand_left",
      "oink-end",
    },
    oinktail = {
      "stand",
      "stand_left",
      "oinkbutt",
    },
    oinktail_left = {
      "stand",
      "stand_left",
      "oinkbutt",
    },
    oinkstart = {
      "stand",
      "stand_left",
      "oinktail",
    },
    oinkstart_left = {
      "stand",
      "stand_left",
      "oinktail",
    },
    salto_end = {
      "stand",
      "stand_left",
    },
    salto_end_left = {
      "stand",
      "stand_left",
    },
    salto = {
      "stand",
      "stand_left",
      "salto_end",
    },
    salto_left = {
      "stand",
      "stand_left",
      "salto_end",
    },
    salto_start = {
      "stand",
      "stand_left",
      "salto",
    },
    salto_start_left = {
      "stand",
      "stand_left",
      "salto",
    },
    salto2 = {
      "stand",
      "stand_left",
      "salto_end",
    },
    salto2_left = {
      "stand",
      "stand_left",
      "salto_end",
    },
    salto_start2 = {
      "stand",
      "stand_left",
      "salto2",
    },
    salto_start2_left = {
      "stand",
      "stand_left",
      "salto2",
    },
    flip_end = {
      "stand",
      "stand_left",
    },
    flip_end_left = {
      "stand",
      "stand_left",
    },
    flip = {
      "stand",
      "stand_left",
      "flip_end",
    },
    flip_left = {
      "stand",
      "stand_left",
      "flip_end",
    },
    flip_start = {
      "stand",
      "stand_left",
      "flip",
    },
    flip_start_left = {
      "stand",
      "stand_left",
      "flip",
    },
    oinkprestart = {
      "stand",
      "stand_left",
      "oinkstart",
    },
    oinkprestart_left = {
      "stand",
      "stand_left",
      "oinkstart",
    },
    sit = {
      "stand",
      "stand_left",
    },
    sit_left = {
      "stand",
      "stand_left",
    },
    ["epic rearing"] = {
      "stand",
      "stand_left",
    },
    ["epic rearing_left"] = {
      "stand",
      "stand_left",
    },
    ["epic rearing2"] = {
      "stand",
      "stand_left",
      "galopp",
    },
    ["epic rearing2_left"] = {
      "stand",
      "stand_left",
      "galopp",
    },
    canoncake = {
      "stand",
      "stand_left",
    },
    canoncake_left = {
      "stand",
      "stand_left",
    },
    canoncake2 = {
      "stand",
      "stand_left",
    },
    canoncake2_left = {
      "stand",
      "stand_left",
    },
    galopp = {
      "stand",
      "stand_left",
    },
    galopp_left = {
      "stand",
      "stand_left",
    },
    ["conga start"] = {
      "stand",
      "stand_left",
      "Conga",
    },
    ["conga start_left"] = {
      "stand",
      "stand_left",
      "Conga",
    },
    conga = {
      "stand",
      "stand_left",
    },
    conga_left = {
      "stand",
      "stand_left",
    },
    chicken2 = {
      "stand",
      "stand_left",
    },
    chicken2_left = {
      "stand",
      "stand_left",
    },
    fluttercuddle_left = {
      "stand",
      "stand_left",
    },
    fluttercuddle_right = {
      "stand",
      "stand_left",
    },
    crystallized = {
      "stand",
      "stand_left",
    },
    crystallized_left = {
      "stand",
      "stand_left",
    },
    goto_gala = {
      "stand",
      "stand_left",
      "gala_stand",
    },
    goto_gala_left = {
      "stand",
      "stand_left",
      "gala_stand",
    },
    gala_stand = {
      "stand",
      "stand_left",
    },
    gala_stand_left = {
      "stand",
      "stand_left",
    },
    gala_trot = {
      "stand",
      "stand_left",
    },
    gala_trot_left = {
      "stand",
      "stand_left",
    },
    ["gala_trot n_n"] = {
      "stand",
      "stand_left",
    },
    ["gala_trot n_n_left"] = {
      "stand",
      "stand_left",
    },
    gala_bounce = {
      "stand",
      "stand_left",
    },
    gala_bounce_left = {
      "stand",
      "stand_left",
    },
    ["gala_bounce n_n"] = {
      "stand",
      "stand_left",
    },
    ["gala_bounce n_n_left"] = {
      "stand",
      "stand_left",
    },
    gala_drag = {
      "stand",
      "stand_left",
    },
    gala_drag_left = {
      "stand",
      "stand_left",
    },
    ["ponko poe gala"] = {
      "stand",
      "stand_left",
    },
    ["ponko poe gala_left"] = {
      "stand",
      "stand_left",
    },
    ["theme 1 gala"] = {
      "stand",
      "stand_left",
    },
    ["theme 1 gala_left"] = {
      "stand",
      "stand_left",
    },
    leave_gala = {
      "stand",
      "stand_left",
    },
    leave_gala_left = {
      "stand",
      "stand_left",
    },
    breezie = {
      "stand",
      "stand_left",
    },
    breezie_left = {
      "stand",
      "stand_left",
    },
    sleep1 = {
      "stand",
      "stand_left",
    },
    sleep1_left = {
      "stand",
      "stand_left",
    },
    weddingdance_start = {
      "stand",
      "stand_left",
      "weddingdance",
    },
    weddingdance_start_left = {
      "stand",
      "stand_left",
      "weddingdance",
    },
    weddingdance = {
      "stand",
      "stand_left",
    },
    weddingdance_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "walk_n_n",
    "walk_n_n_left",
    "parade",
    "parade_left",
    "bounce",
    "bounce_left",
    "bounce_n_n",
    "bounce_n_n_left",
    "bounce_up",
    "bounce_up_left",
    "parasprite_follow_circle1",
    "parasprite_follow_circle1_left",
    "parasprite_follow_circle2",
    "parasprite_follow_circle2_left",
    "parasprite_follow_circle3",
    "parasprite_follow_circle3_left",
    "parasprite_follow_circle4",
    "parasprite_follow_circle4_left",
    "parasprite_follow_circle5",
    "parasprite_follow_circle5_left",
    "theme 1",
    "theme 1_left",
    "pinkie_balloon_poke",
    "pinkie_balloon_poke_left",
    "stalking_start",
    "stalking_start_left",
    "stalking_dash",
    "stalking_dash_left",
    "stalking_stop",
    "stalking_stop_left",
    "wink",
    "wink_left",
    "drag",
    "drag_left",
    "mouseover",
    "mouseover_left",
    "hatersgonnahate",
    "hatersgonnahate_left",
    "haterstart",
    "haterstart_left",
    "giggle",
    "giggle_left",
    "jumpturn",
    "jumpturn_left",
    "jumpturnpl",
    "jumpturnpl_left",
    "flower1",
    "flower1_left",
    "walk2",
    "walk2_left",
    "jumpy",
    "jumpy_left",
    "rollfinish",
    "rollfinish_left",
    "rollend",
    "rollend_left",
    "rollsequence",
    "rollsequence_left",
    "rollstart",
    "rollstart_left",
    "rolljump",
    "rolljump_left",
    "rollfinish2",
    "rollfinish2_left",
    "rollend2",
    "rollend2_left",
    "rollsequence2",
    "rollsequence2_left",
    "rollstart2",
    "rollstart2_left",
    "rolljump2",
    "rolljump2_left",
    "rolltransition",
    "rolltransition_left",
    "hick1",
    "hick1_left",
    "hick2mix",
    "hick2mix_left",
    "rofl",
    "rofl_left",
    "hick3",
    "hick3_left",
    "jumpflower",
    "jumpflower_left",
    "jumppreflowe",
    "jumppreflowe_left",
    "flower2",
    "flower2_left",
    "flower3",
    "flower3_left",
    "tongue",
    "tongue_left",
    "flower6",
    "flower6_left",
    "flower5",
    "flower5_left",
    "flower4mix",
    "flower4mix_left",
    "flower7",
    "flower7_left",
    "jumpflower2",
    "jumpflower2_left",
    "jumppreflowe2",
    "jumppreflowe2_left",
    "jumpflower3",
    "jumpflower3_left",
    "jumppreflowe3",
    "jumppreflowe3_left",
    "cupcake",
    "cupcake_left",
    "chicken",
    "chicken_left",
    "sleep",
    "sleep_left",
    "rest",
    "rest_left",
    "pinkacopter",
    "pinkacopter_left",
    "pinkacopter2",
    "pinkacopter2_left",
    "pinkacopter3",
    "pinkacopter3_left",
    "pinkacopter4",
    "pinkacopter4_left",
    "pinkacopter5",
    "pinkacopter5_left",
    "pinkacopter_start",
    "pinkacopter_start_left",
    "pinkacopter_begin",
    "pinkacopter_begin_left",
    "pinkacopter_stop",
    "pinkacopter_stop_left",
    "backtrack",
    "backtrack_left",
    "parasprite_stop",
    "parasprite_stop_left",
    "parade_start",
    "parade_start_left",
    "parasprite_follow_circle",
    "parasprite_follow_circle_left",
    "dance_tongue",
    "dance_tongue_left",
    "haters_stop",
    "haters_stop_left",
    "princess",
    "princess_left",
    "cartwheel",
    "cartwheel_left",
    "sittinggiggle",
    "sittinggiggle_left",
    "sneeze_stop",
    "sneeze_stop_left",
    "sneeze_fly",
    "sneeze_fly_left",
    "sneeze_start",
    "sneeze_start_left",
    "sneeze_cute",
    "sneeze_cute_left",
    "parasoloff",
    "parasoloff_left",
    "twitchyrun",
    "twitchyrun_left",
    "parasolon",
    "parasolon_left",
    "twitchytail",
    "twitchytail_left",
    "parasolon2",
    "parasolon2_left",
    "twitchytail2",
    "twitchytail2_left",
    "bite_left",
    "bite_right",
    "pose",
    "pose_left",
    "hickup_start_1",
    "hickup_start_1_left",
    "hickup_start_1-2",
    "hickup_start_1-2_left",
    "hickup_start_2",
    "hickup_start_2_left",
    "hickup_start_2-2",
    "hickup_start_2-2_left",
    "hickup_start_3",
    "hickup_start_3_left",
    "hickup_start_3-2",
    "hickup_start_3-2_left",
    "hickup_start_4",
    "hickup_start_4_left",
    "hickup_start_4-2",
    "hickup_start_4-2_left",
    "hickup_stop",
    "hickup_stop_left",
    "sitrofl",
    "sitrofl_left",
    "rofls2stop",
    "rofls2stop_left",
    "rofls2",
    "rofls2_left",
    "rofls2start",
    "rofls2start_left",
    "crocodance",
    "crocodance_left",
    "teleportreappear",
    "teleportreappear_left",
    "teleport run",
    "pinkaport",
    "pinkaport_left",
    "cannonshoot",
    "cannonshoot_left",
    "cannonrun",
    "cannonrun_left",
    "cannostart",
    "cannostart_left",
    "cannonfull",
    "cannonfull_left",
    "ponko poe",
    "ponko poe_left",
    "oink-end",
    "oink-end_left",
    "oinkbutt",
    "oinkbutt_left",
    "oinktail",
    "oinktail_left",
    "oinkstart",
    "oinkstart_left",
    "salto_end",
    "salto_end_left",
    "salto",
    "salto_left",
    "salto_start",
    "salto_start_left",
    "salto2",
    "salto2_left",
    "salto_start2",
    "salto_start2_left",
    "flip_end",
    "flip_end_left",
    "flip",
    "flip_left",
    "flip_start",
    "flip_start_left",
    "oinkprestart",
    "oinkprestart_left",
    "sit",
    "sit_left",
    "epic rearing",
    "epic rearing_left",
    "epic rearing2",
    "epic rearing2_left",
    "canoncake",
    "canoncake_left",
    "canoncake2",
    "canoncake2_left",
    "galopp",
    "galopp_left",
    "conga start",
    "conga start_left",
    "conga",
    "conga_left",
    "chicken2",
    "chicken2_left",
    "fluttercuddle_left",
    "fluttercuddle_right",
    "crystallized",
    "crystallized_left",
    "goto_gala",
    "goto_gala_left",
    "gala_stand",
    "gala_stand_left",
    "gala_trot",
    "gala_trot_left",
    "gala_trot n_n",
    "gala_trot n_n_left",
    "gala_bounce",
    "gala_bounce_left",
    "gala_bounce n_n",
    "gala_bounce n_n_left",
    "gala_drag",
    "gala_drag_left",
    "ponko poe gala",
    "ponko poe gala_left",
    "theme 1 gala",
    "theme 1 gala_left",
    "leave_gala",
    "leave_gala_left",
    "breezie",
    "breezie_left",
    "sleep1",
    "sleep1_left",
    "weddingdance_start",
    "weddingdance_start_left",
    "weddingdance",
    "weddingdance_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "walk",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "walk_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}