return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "theme 1",
      "theme 1_left",
      "theme 2",
      "theme 2_left",
      "theme 3",
      "theme 3_left",
      "theme 5",
      "theme 5_left",
      "theme 6",
      "theme 6_left",
      "theme 4",
      "theme 4_left",
      "fly",
      "fly_left",
      "scroll_arrive",
      "scroll_arrive_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "theme 1",
      "theme 1_left",
      "theme 2",
      "theme 2_left",
      "theme 3",
      "theme 3_left",
      "theme 5",
      "theme 5_left",
      "theme 6",
      "theme 6_left",
      "theme 4",
      "theme 4_left",
      "fly",
      "fly_left",
      "scroll_arrive",
      "scroll_arrive_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    ["theme 1"] = {
      "stand",
      "stand_left",
      "theme 2",
    },
    ["theme 1_left"] = {
      "stand",
      "stand_left",
      "theme 2",
    },
    ["theme 2"] = {
      "stand",
      "stand_left",
      "theme 3",
    },
    ["theme 2_left"] = {
      "stand",
      "stand_left",
      "theme 3",
    },
    ["theme 3"] = {
      "stand",
      "stand_left",
      "theme 4",
    },
    ["theme 3_left"] = {
      "stand",
      "stand_left",
      "theme 4",
    },
    ["theme 5"] = {
      "stand",
      "stand_left",
      "theme 6",
    },
    ["theme 5_left"] = {
      "stand",
      "stand_left",
      "theme 6",
    },
    ["theme 6"] = {
      "stand",
      "stand_left",
    },
    ["theme 6_left"] = {
      "stand",
      "stand_left",
    },
    ["theme 4"] = {
      "stand",
      "stand_left",
      "theme 5",
    },
    ["theme 4_left"] = {
      "stand",
      "stand_left",
      "theme 5",
    },
    fly = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    scroll_arrive = {
      "stand",
      "stand_left",
    },
    scroll_arrive_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "theme 1",
    "theme 1_left",
    "theme 2",
    "theme 2_left",
    "theme 3",
    "theme 3_left",
    "theme 5",
    "theme 5_left",
    "theme 6",
    "theme 6_left",
    "theme 4",
    "theme 4_left",
    "scroll_arrive",
    "scroll_arrive_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
        "fly",
      },
      fast = {
        "walk",
        "fly",
      },
      slow = {
        "walk",
        "fly",
      },
    },
    left = {
      normal = {
        "walk_left",
        "fly_left",
      },
      fast = {
        "walk_left",
        "fly_left",
      },
      slow = {
        "walk_left",
        "fly_left",
      },
    },
  },
}