return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
      "fly",
      "fly_left",
      "zoom",
      "zoom_left",
      "starswirl",
      "starswirl_left",
      "crystallized",
      "crystallized_left",
      "transformation start r",
      "transformation finish r",
      "transformation start l",
      "transformation finish l",
      "dress stand",
      "dress stand_left",
      "dress stand r",
      "dress stand l",
      "dress walk",
      "dress walk_left",
      "dress walk-wings",
      "dress walk-wings_left",
      "dress fly",
      "dress fly_left",
      "dress transformation start r",
      "dress transformation finish r",
      "dress transformation start l",
      "dress transformation finish l",
      "breezie",
      "breezie_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
      "fly",
      "fly_left",
      "zoom",
      "zoom_left",
      "starswirl",
      "starswirl_left",
      "crystallized",
      "crystallized_left",
      "transformation start r",
      "transformation finish r",
      "transformation start l",
      "transformation finish l",
      "dress stand",
      "dress stand_left",
      "dress stand r",
      "dress stand l",
      "dress walk",
      "dress walk_left",
      "dress walk-wings",
      "dress walk-wings_left",
      "dress fly",
      "dress fly_left",
      "dress transformation start r",
      "dress transformation finish r",
      "dress transformation start l",
      "dress transformation finish l",
      "breezie",
      "breezie_left",
    },
    ["stand r"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
      "fly",
      "fly_left",
      "zoom",
      "zoom_left",
      "starswirl",
      "starswirl_left",
      "crystallized",
      "crystallized_left",
      "transformation start r",
      "transformation finish r",
      "transformation start l",
      "transformation finish l",
      "dress stand",
      "dress stand_left",
      "dress stand r",
      "dress stand l",
      "dress walk",
      "dress walk_left",
      "dress walk-wings",
      "dress walk-wings_left",
      "dress fly",
      "dress fly_left",
      "dress transformation start r",
      "dress transformation finish r",
      "dress transformation start l",
      "dress transformation finish l",
      "breezie",
      "breezie_left",
    },
    ["stand l"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
      "fly",
      "fly_left",
      "zoom",
      "zoom_left",
      "starswirl",
      "starswirl_left",
      "crystallized",
      "crystallized_left",
      "transformation start r",
      "transformation finish r",
      "transformation start l",
      "transformation finish l",
      "dress stand",
      "dress stand_left",
      "dress stand r",
      "dress stand l",
      "dress walk",
      "dress walk_left",
      "dress walk-wings",
      "dress walk-wings_left",
      "dress fly",
      "dress fly_left",
      "dress transformation start r",
      "dress transformation finish r",
      "dress transformation start l",
      "dress transformation finish l",
      "breezie",
      "breezie_left",
    },
    walk = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
      "gallop",
      "gallop_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
      "gallop",
      "gallop_left",
    },
    ["walk-wings"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "fly",
      "fly_left",
      "gallop",
      "gallop_left",
    },
    ["walk-wings_left"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "fly",
      "fly_left",
      "gallop",
      "gallop_left",
    },
    fly = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
    },
    zoom = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    zoom_left = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    starswirl = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    starswirl_left = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    gallop = {
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
    },
    gallop_left = {
      "walk",
      "walk_left",
      "walk-wings",
      "walk-wings_left",
    },
    crystallized = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    crystallized_left = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["transformation start r"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "dress transformation finish r",
    },
    ["transformation finish r"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["transformation start l"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "dress transformation finish l",
    },
    ["transformation finish l"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress stand"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress stand_left"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress stand r"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress stand l"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress walk"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress walk_left"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress walk-wings"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress walk-wings_left"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress fly"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress fly_left"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    ["dress transformation start r"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "transformation finish r",
    },
    ["dress transformation finish r"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "dress stand r",
    },
    ["dress transformation start l"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "transformation finish l",
    },
    ["dress transformation finish l"] = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
      "dress stand l",
    },
    breezie = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
    breezie_left = {
      "stand",
      "stand_left",
      "stand r",
      "stand l",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "stand r",
    "stand l",
    "walk-wings",
    "walk-wings_left",
    "zoom",
    "zoom_left",
    "starswirl",
    "starswirl_left",
    "crystallized",
    "crystallized_left",
    "transformation start r",
    "transformation finish r",
    "transformation start l",
    "transformation finish l",
    "dress stand",
    "dress stand_left",
    "dress stand r",
    "dress stand l",
    "dress walk",
    "dress walk_left",
    "dress walk-wings",
    "dress walk-wings_left",
    "dress fly",
    "dress fly_left",
    "dress transformation start r",
    "dress transformation finish r",
    "dress transformation start l",
    "dress transformation finish l",
    "breezie",
    "breezie_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
        "fly",
      },
      fast = {
        "gallop",
      },
      slow = {
        "walk",
        "fly",
      },
    },
    left = {
      normal = {
        "walk_left",
        "fly_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {
        "walk_left",
        "fly_left",
      },
    },
  },
}