return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "flyfast",
      "flyfast_left",
      "rainboom1",
      "rainboom1_left",
      "rainboom2",
      "rainboom2_left",
      "rainboom3",
      "rainboom3_left",
      "rainboom4",
      "rainboom4_left",
      "rainboom5",
      "rainboom5_left",
      "fly",
      "fly_left",
      "hover",
      "hover_left",
      "leap_start",
      "leap_start_left",
      "leap",
      "leap_left",
      "leap_end",
      "leap_end_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "flyfast",
      "flyfast_left",
      "rainboom1",
      "rainboom1_left",
      "rainboom2",
      "rainboom2_left",
      "rainboom3",
      "rainboom3_left",
      "rainboom4",
      "rainboom4_left",
      "rainboom5",
      "rainboom5_left",
      "fly",
      "fly_left",
      "hover",
      "hover_left",
      "leap_start",
      "leap_start_left",
      "leap",
      "leap_left",
      "leap_end",
      "leap_end_left",
    },
    trot = {
      "fly",
      "fly_left",
    },
    trot_left = {
      "fly",
      "fly_left",
    },
    flyfast = {
      "stand",
      "stand_left",
    },
    flyfast_left = {
      "stand",
      "stand_left",
    },
    rainboom1 = {
      "stand",
      "stand_left",
      "RainBoom2",
    },
    rainboom1_left = {
      "stand",
      "stand_left",
      "RainBoom2",
    },
    rainboom2 = {
      "stand",
      "stand_left",
      "RainBoom3",
    },
    rainboom2_left = {
      "stand",
      "stand_left",
      "RainBoom3",
    },
    rainboom3 = {
      "stand",
      "stand_left",
      "RainBoom4",
    },
    rainboom3_left = {
      "stand",
      "stand_left",
      "RainBoom4",
    },
    rainboom4 = {
      "stand",
      "stand_left",
      "RainBoom5",
    },
    rainboom4_left = {
      "stand",
      "stand_left",
      "RainBoom5",
    },
    rainboom5 = {
      "stand",
      "stand_left",
    },
    rainboom5_left = {
      "stand",
      "stand_left",
    },
    fly = {
      "stand",
      "stand_left",
      "trot",
      "trot_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "trot",
      "trot_left",
    },
    hover = {
      "stand",
      "stand_left",
    },
    hover_left = {
      "stand",
      "stand_left",
    },
    leap_start = {
      "stand",
      "stand_left",
      "Leap",
    },
    leap_start_left = {
      "stand",
      "stand_left",
      "Leap",
    },
    leap = {
      "stand",
      "stand_left",
      "Leap_end",
    },
    leap_left = {
      "stand",
      "stand_left",
      "Leap_end",
    },
    leap_end = {
      "stand",
      "stand_left",
    },
    leap_end_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "flyfast",
    "flyfast_left",
    "rainboom1",
    "rainboom1_left",
    "rainboom2",
    "rainboom2_left",
    "rainboom3",
    "rainboom3_left",
    "rainboom4",
    "rainboom4_left",
    "rainboom5",
    "rainboom5_left",
    "hover",
    "hover_left",
    "leap_start",
    "leap_start_left",
    "leap",
    "leap_left",
    "leap_end",
    "leap_end_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
      },
      fast = {
        "gallop",
      },
      slow = {
        "fly",
      },
    },
    left = {
      normal = {
        "gallop_left",
        "fly_left",
      },
      fast = {
        "gallop_left",
        "fly_left",
      },
      slow = {
        "fly_left",
      },
    },
  },
}