return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "flyzoom",
      "flyzoom_left",
      "fly",
      "fly_left",
      "dash",
      "dash_left",
      "walk",
      "walk_left",
      "walk_wings",
      "walk_wings_left",
      "makerain",
      "makerain_left",
      "sleep",
      "sleep_left",
      "hover",
      "hover_left",
      "junior speedsters 1",
      "junior speedsters 1_left",
      "junior speedsters 2",
      "junior speedsters 2_left",
      "junior speedsters 3",
      "junior speedsters 3_left",
      "junior speedsters 4",
      "junior speedsters 4_left",
      "junior speedsters 5",
      "junior speedsters 5_left",
      "junior speedsters 6",
      "junior speedsters 6_left",
      "theme 1",
      "theme 1_left",
      "galla_dress",
      "galla_dress_left",
      "dash_ground",
      "dash_ground_left",
      "dinodash",
      "dinodash_left",
      "drag",
      "drag_left",
      "ronbodosh",
      "ronbodosh_left",
      "beep",
      "beep_left",
      "conga",
      "conga_left",
      "dizzy",
      "dizzy_left",
      "salute",
      "training",
      "training_left",
      "coaching",
      "coaching_left",
      "crystallized",
      "crystallized_left",
      "breezie",
      "breezie_left",
      "swim",
      "swim_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "flyzoom",
      "flyzoom_left",
      "fly",
      "fly_left",
      "dash",
      "dash_left",
      "walk",
      "walk_left",
      "walk_wings",
      "walk_wings_left",
      "makerain",
      "makerain_left",
      "sleep",
      "sleep_left",
      "hover",
      "hover_left",
      "junior speedsters 1",
      "junior speedsters 1_left",
      "junior speedsters 2",
      "junior speedsters 2_left",
      "junior speedsters 3",
      "junior speedsters 3_left",
      "junior speedsters 4",
      "junior speedsters 4_left",
      "junior speedsters 5",
      "junior speedsters 5_left",
      "junior speedsters 6",
      "junior speedsters 6_left",
      "theme 1",
      "theme 1_left",
      "galla_dress",
      "galla_dress_left",
      "dash_ground",
      "dash_ground_left",
      "dinodash",
      "dinodash_left",
      "drag",
      "drag_left",
      "ronbodosh",
      "ronbodosh_left",
      "beep",
      "beep_left",
      "conga",
      "conga_left",
      "dizzy",
      "dizzy_left",
      "salute",
      "training",
      "training_left",
      "coaching",
      "coaching_left",
      "crystallized",
      "crystallized_left",
      "breezie",
      "breezie_left",
      "swim",
      "swim_left",
    },
    flyzoom = {
      "stand",
      "stand_left",
    },
    flyzoom_left = {
      "stand",
      "stand_left",
    },
    fly = {
      "stand",
      "stand_left",
    },
    fly_left = {
      "stand",
      "stand_left",
    },
    dash = {
      "stand",
      "stand_left",
    },
    dash_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_wings = {
      "stand",
      "stand_left",
    },
    walk_wings_left = {
      "stand",
      "stand_left",
    },
    makerain = {
      "stand",
      "stand_left",
    },
    makerain_left = {
      "stand",
      "stand_left",
    },
    sleep = {
      "stand",
      "stand_left",
    },
    sleep_left = {
      "stand",
      "stand_left",
    },
    hover = {
      "stand",
      "stand_left",
    },
    hover_left = {
      "stand",
      "stand_left",
    },
    ["junior speedsters 1"] = {
      "stand",
      "stand_left",
      "junior speedsters 2",
    },
    ["junior speedsters 1_left"] = {
      "stand",
      "stand_left",
      "junior speedsters 2",
    },
    ["junior speedsters 2"] = {
      "stand",
      "stand_left",
      "junior speedsters 3",
    },
    ["junior speedsters 2_left"] = {
      "stand",
      "stand_left",
      "junior speedsters 3",
    },
    ["junior speedsters 3"] = {
      "stand",
      "stand_left",
      "junior speedsters 4",
    },
    ["junior speedsters 3_left"] = {
      "stand",
      "stand_left",
      "junior speedsters 4",
    },
    ["junior speedsters 4"] = {
      "stand",
      "stand_left",
      "junior speedsters 5",
    },
    ["junior speedsters 4_left"] = {
      "stand",
      "stand_left",
      "junior speedsters 5",
    },
    ["junior speedsters 5"] = {
      "stand",
      "stand_left",
      "junior speedsters 6",
    },
    ["junior speedsters 5_left"] = {
      "stand",
      "stand_left",
      "junior speedsters 6",
    },
    ["junior speedsters 6"] = {
      "stand",
      "stand_left",
    },
    ["junior speedsters 6_left"] = {
      "stand",
      "stand_left",
    },
    ["theme 1"] = {
      "stand",
      "stand_left",
    },
    ["theme 1_left"] = {
      "stand",
      "stand_left",
    },
    galla_dress = {
      "stand",
      "stand_left",
    },
    galla_dress_left = {
      "stand",
      "stand_left",
    },
    dash_ground = {
      "stand",
      "stand_left",
    },
    dash_ground_left = {
      "stand",
      "stand_left",
    },
    dinodash = {
      "stand",
      "stand_left",
    },
    dinodash_left = {
      "stand",
      "stand_left",
    },
    drag = {
      "stand",
      "stand_left",
    },
    drag_left = {
      "stand",
      "stand_left",
    },
    ronbodosh = {
      "stand",
      "stand_left",
    },
    ronbodosh_left = {
      "stand",
      "stand_left",
    },
    beep = {
      "stand",
      "stand_left",
    },
    beep_left = {
      "stand",
      "stand_left",
    },
    conga = {
      "stand",
      "stand_left",
    },
    conga_left = {
      "stand",
      "stand_left",
    },
    dizzy = {
      "stand",
      "stand_left",
    },
    dizzy_left = {
      "stand",
      "stand_left",
    },
    salute = {
      "stand",
      "stand_left",
    },
    training = {
      "stand",
      "stand_left",
    },
    training_left = {
      "stand",
      "stand_left",
    },
    coaching = {
      "stand",
      "stand_left",
    },
    coaching_left = {
      "stand",
      "stand_left",
    },
    crystallized = {
      "stand",
      "stand_left",
    },
    crystallized_left = {
      "stand",
      "stand_left",
    },
    breezie = {
      "stand",
      "stand_left",
    },
    breezie_left = {
      "stand",
      "stand_left",
    },
    swim = {
      "stand",
      "stand_left",
    },
    swim_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "flyzoom",
    "flyzoom_left",
    "dash",
    "dash_left",
    "walk_wings",
    "walk_wings_left",
    "makerain",
    "makerain_left",
    "sleep",
    "sleep_left",
    "hover",
    "hover_left",
    "junior speedsters 1",
    "junior speedsters 1_left",
    "junior speedsters 2",
    "junior speedsters 2_left",
    "junior speedsters 3",
    "junior speedsters 3_left",
    "junior speedsters 4",
    "junior speedsters 4_left",
    "junior speedsters 5",
    "junior speedsters 5_left",
    "junior speedsters 6",
    "junior speedsters 6_left",
    "theme 1",
    "theme 1_left",
    "galla_dress",
    "galla_dress_left",
    "dash_ground",
    "dash_ground_left",
    "dinodash",
    "dinodash_left",
    "drag",
    "drag_left",
    "ronbodosh",
    "ronbodosh_left",
    "beep",
    "beep_left",
    "conga",
    "conga_left",
    "dizzy",
    "dizzy_left",
    "salute",
    "training",
    "training_left",
    "coaching",
    "coaching_left",
    "crystallized",
    "crystallized_left",
    "breezie",
    "breezie_left",
    "swim",
    "swim_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
        "walk",
      },
      fast = {
        "fly",
        "walk",
      },
      slow = {
        "fly",
        "walk",
      },
    },
    left = {
      normal = {
        "fly_left",
        "walk_left",
      },
      fast = {
        "fly_left",
        "walk_left",
      },
      slow = {
        "fly_left",
        "walk_left",
      },
    },
  },
}