return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "dragged",
      "dragged_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "walk_diagonal",
      "walk_diagonal_left",
      "horn_shine_false",
      "horn_shine_false_left",
      "horn_shine_true",
      "horn_shine_true_left",
      "pull",
      "pull_left",
      "pull_2",
      "pull_2_left",
      "drag_1",
      "drag_1_left",
      "drag_2",
      "drag_2_left",
      "drag_3",
      "drag_3_left",
      "smile",
      "smile_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "dragged",
      "dragged_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "walk_diagonal",
      "walk_diagonal_left",
      "horn_shine_false",
      "horn_shine_false_left",
      "horn_shine_true",
      "horn_shine_true_left",
      "pull",
      "pull_left",
      "pull_2",
      "pull_2_left",
      "drag_1",
      "drag_1_left",
      "drag_2",
      "drag_2_left",
      "drag_3",
      "drag_3_left",
      "smile",
      "smile_left",
    },
    dragged = {
      "stand",
      "stand_left",
    },
    dragged_left = {
      "stand",
      "stand_left",
    },
    sleep = {
      "stand",
      "stand_left",
    },
    sleep_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_diagonal = {
      "stand",
      "stand_left",
    },
    walk_diagonal_left = {
      "stand",
      "stand_left",
    },
    horn_shine_false = {
      "stand",
      "stand_left",
    },
    horn_shine_false_left = {
      "stand",
      "stand_left",
    },
    horn_shine_true = {
      "stand",
      "stand_left",
      "pull",
    },
    horn_shine_true_left = {
      "stand",
      "stand_left",
      "pull",
    },
    pull = {
      "stand",
      "stand_left",
      "pull_2",
    },
    pull_left = {
      "stand",
      "stand_left",
      "pull_2",
    },
    pull_2 = {
      "stand",
      "stand_left",
      "drag_1",
    },
    pull_2_left = {
      "stand",
      "stand_left",
      "drag_1",
    },
    drag_1 = {
      "stand",
      "stand_left",
      "drag_2",
    },
    drag_1_left = {
      "stand",
      "stand_left",
      "drag_2",
    },
    drag_2 = {
      "stand",
      "stand_left",
      "drag_3",
    },
    drag_2_left = {
      "stand",
      "stand_left",
      "drag_3",
    },
    drag_3 = {
      "stand",
      "stand_left",
    },
    drag_3_left = {
      "stand",
      "stand_left",
    },
    smile = {
      "stand",
      "stand_left",
    },
    smile_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "dragged",
    "dragged_left",
    "sleep",
    "sleep_left",
    "walk_diagonal",
    "walk_diagonal_left",
    "horn_shine_false",
    "horn_shine_false_left",
    "horn_shine_true",
    "horn_shine_true_left",
    "pull",
    "pull_left",
    "pull_2",
    "pull_2_left",
    "drag_1",
    "drag_1_left",
    "drag_2",
    "drag_2_left",
    "drag_3",
    "drag_3_left",
    "smile",
    "smile_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "walk",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "walk_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}