return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly0",
      "fly0_left",
      "fly1",
      "fly1_left",
      "theme 1",
      "theme 1_left",
      "admire_rarity_start",
      "admire_rarity_start_left",
      "admire_rarity",
      "admire_rarity_left",
      "follow_rarity",
      "follow_rarity_left",
      "galla_dress",
      "galla_dress_left",
      "ponder",
      "ponder_left",
      "drama couch",
      "drama couch_left",
      "rarara",
      "rarara_left",
      "tantrum",
      "tantrum_left",
      "sleep 1",
      "sleep 1_left",
      "sleep 2",
      "sleep 2_left",
      "fashion show",
      "fashion show_left",
      "conga",
      "conga_left",
      "drag",
      "drag_left",
      "crystallized",
      "crystallized_left",
      "farmpony_start",
      "farmpony_start_left",
      "farm_stand",
      "farm_stand_left",
      "farm_stand1",
      "farm_stand1_left",
      "farm_stand2",
      "farm_stand2_left",
      "farm_walk",
      "farm_walk_left",
      "farm_walk1",
      "farm_walk1_left",
      "farm_walk2",
      "farm_walk2_left",
      "farm_scratch",
      "farm_scratch_left",
      "farmpony_end",
      "farmpony_end_left",
      "farm_drag",
      "farm_drag_left",
      "breezie",
      "breezie_left",
      "somebodycallthefashionpolice",
      "somebodycallthefashionpolice_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly0",
      "fly0_left",
      "fly1",
      "fly1_left",
      "theme 1",
      "theme 1_left",
      "admire_rarity_start",
      "admire_rarity_start_left",
      "admire_rarity",
      "admire_rarity_left",
      "follow_rarity",
      "follow_rarity_left",
      "galla_dress",
      "galla_dress_left",
      "ponder",
      "ponder_left",
      "drama couch",
      "drama couch_left",
      "rarara",
      "rarara_left",
      "tantrum",
      "tantrum_left",
      "sleep 1",
      "sleep 1_left",
      "sleep 2",
      "sleep 2_left",
      "fashion show",
      "fashion show_left",
      "conga",
      "conga_left",
      "drag",
      "drag_left",
      "crystallized",
      "crystallized_left",
      "farmpony_start",
      "farmpony_start_left",
      "farm_stand",
      "farm_stand_left",
      "farm_stand1",
      "farm_stand1_left",
      "farm_stand2",
      "farm_stand2_left",
      "farm_walk",
      "farm_walk_left",
      "farm_walk1",
      "farm_walk1_left",
      "farm_walk2",
      "farm_walk2_left",
      "farm_scratch",
      "farm_scratch_left",
      "farmpony_end",
      "farmpony_end_left",
      "farm_drag",
      "farm_drag_left",
      "breezie",
      "breezie_left",
      "somebodycallthefashionpolice",
      "somebodycallthefashionpolice_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    fly0 = {
      "stand",
      "stand_left",
      "fly1",
    },
    fly0_left = {
      "stand",
      "stand_left",
      "fly1",
    },
    fly1 = {
      "stand",
      "stand_left",
    },
    fly1_left = {
      "stand",
      "stand_left",
    },
    ["theme 1"] = {
      "stand",
      "stand_left",
    },
    ["theme 1_left"] = {
      "stand",
      "stand_left",
    },
    admire_rarity_start = {
      "stand",
      "stand_left",
      "Admire_Rarity",
    },
    admire_rarity_start_left = {
      "stand",
      "stand_left",
      "Admire_Rarity",
    },
    admire_rarity = {
      "stand",
      "stand_left",
    },
    admire_rarity_left = {
      "stand",
      "stand_left",
    },
    follow_rarity = {
      "stand",
      "stand_left",
    },
    follow_rarity_left = {
      "stand",
      "stand_left",
    },
    galla_dress = {
      "stand",
      "stand_left",
    },
    galla_dress_left = {
      "stand",
      "stand_left",
    },
    ponder = {
      "stand",
      "stand_left",
    },
    ponder_left = {
      "stand",
      "stand_left",
    },
    ["drama couch"] = {
      "stand",
      "stand_left",
    },
    ["drama couch_left"] = {
      "stand",
      "stand_left",
    },
    rarara = {
      "stand",
      "stand_left",
      "Fashion Show",
    },
    rarara_left = {
      "stand",
      "stand_left",
      "Fashion Show",
    },
    tantrum = {
      "stand",
      "stand_left",
    },
    tantrum_left = {
      "stand",
      "stand_left",
    },
    ["sleep 1"] = {
      "stand",
      "stand_left",
    },
    ["sleep 1_left"] = {
      "stand",
      "stand_left",
    },
    ["sleep 2"] = {
      "stand",
      "stand_left",
    },
    ["sleep 2_left"] = {
      "stand",
      "stand_left",
    },
    ["fashion show"] = {
      "stand",
      "stand_left",
    },
    ["fashion show_left"] = {
      "stand",
      "stand_left",
    },
    conga = {
      "stand",
      "stand_left",
    },
    conga_left = {
      "stand",
      "stand_left",
    },
    drag = {
      "stand",
      "stand_left",
    },
    drag_left = {
      "stand",
      "stand_left",
    },
    crystallized = {
      "stand",
      "stand_left",
    },
    crystallized_left = {
      "stand",
      "stand_left",
    },
    farmpony_start = {
      "stand",
      "stand_left",
      "farm_stand",
    },
    farmpony_start_left = {
      "stand",
      "stand_left",
      "farm_stand",
    },
    farm_stand = {
      "stand",
      "stand_left",
    },
    farm_stand_left = {
      "stand",
      "stand_left",
    },
    farm_stand1 = {
      "stand",
      "stand_left",
    },
    farm_stand1_left = {
      "stand",
      "stand_left",
    },
    farm_stand2 = {
      "stand",
      "stand_left",
    },
    farm_stand2_left = {
      "stand",
      "stand_left",
    },
    farm_walk = {
      "stand",
      "stand_left",
    },
    farm_walk_left = {
      "stand",
      "stand_left",
    },
    farm_walk1 = {
      "stand",
      "stand_left",
    },
    farm_walk1_left = {
      "stand",
      "stand_left",
    },
    farm_walk2 = {
      "stand",
      "stand_left",
    },
    farm_walk2_left = {
      "stand",
      "stand_left",
    },
    farm_scratch = {
      "stand",
      "stand_left",
    },
    farm_scratch_left = {
      "stand",
      "stand_left",
    },
    farmpony_end = {
      "stand",
      "stand_left",
    },
    farmpony_end_left = {
      "stand",
      "stand_left",
    },
    farm_drag = {
      "stand",
      "stand_left",
    },
    farm_drag_left = {
      "stand",
      "stand_left",
    },
    breezie = {
      "stand",
      "stand_left",
    },
    breezie_left = {
      "stand",
      "stand_left",
    },
    somebodycallthefashionpolice = {
      "stand",
      "stand_left",
    },
    somebodycallthefashionpolice_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "fly0",
    "fly0_left",
    "fly1",
    "fly1_left",
    "theme 1",
    "theme 1_left",
    "admire_rarity_start",
    "admire_rarity_start_left",
    "admire_rarity",
    "admire_rarity_left",
    "follow_rarity",
    "follow_rarity_left",
    "galla_dress",
    "galla_dress_left",
    "ponder",
    "ponder_left",
    "drama couch",
    "drama couch_left",
    "rarara",
    "rarara_left",
    "tantrum",
    "tantrum_left",
    "sleep 1",
    "sleep 1_left",
    "sleep 2",
    "sleep 2_left",
    "fashion show",
    "fashion show_left",
    "conga",
    "conga_left",
    "drag",
    "drag_left",
    "crystallized",
    "crystallized_left",
    "farmpony_start",
    "farmpony_start_left",
    "farm_stand",
    "farm_stand_left",
    "farm_stand1",
    "farm_stand1_left",
    "farm_stand2",
    "farm_stand2_left",
    "farm_walk",
    "farm_walk_left",
    "farm_walk1",
    "farm_walk1_left",
    "farm_walk2",
    "farm_walk2_left",
    "farm_scratch",
    "farm_scratch_left",
    "farmpony_end",
    "farmpony_end_left",
    "farm_drag",
    "farm_drag_left",
    "breezie",
    "breezie_left",
    "somebodycallthefashionpolice",
    "somebodycallthefashionpolice_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "walk",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "walk_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}