return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
      "scoot_c",
      "scoot_c_left",
      "scoot",
      "scoot_left",
      "basket",
      "basket_left",
      "skip",
      "skip_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
      "scoot_c",
      "scoot_c_left",
      "scoot",
      "scoot_left",
      "basket",
      "basket_left",
      "skip",
      "skip_left",
    },
    walk2 = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
      "fly",
      "fly_left",
    },
    walk2_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
      "fly",
      "fly_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
      "fly",
      "fly_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
      "fly",
      "fly_left",
    },
    gallop = {
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
    },
    gallop_left = {
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
    },
    fly = {
      "stand",
      "stand_left",
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "walk2",
      "walk2_left",
      "walk",
      "walk_left",
    },
    scoot_c = {
      "stand",
      "stand_left",
    },
    scoot_c_left = {
      "stand",
      "stand_left",
    },
    scoot = {
      "stand",
      "stand_left",
    },
    scoot_left = {
      "stand",
      "stand_left",
    },
    basket = {
      "stand",
      "stand_left",
    },
    basket_left = {
      "stand",
      "stand_left",
    },
    skip = {
      "stand",
      "stand_left",
    },
    skip_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "walk2",
    "walk2_left",
    "scoot_c",
    "scoot_c_left",
    "scoot",
    "scoot_left",
    "basket",
    "basket_left",
    "skip",
    "skip_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
        "fly",
      },
      fast = {
        "gallop",
      },
      slow = {
        "walk",
        "fly",
      },
    },
    left = {
      normal = {
        "walk_left",
        "fly_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {
        "walk_left",
        "fly_left",
      },
    },
  },
}