return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "horn0",
      "horn0_left",
      "horn1",
      "horn1_left",
      "horn2",
      "horn2_left",
      "sitting",
      "sitting_left",
      "stretch",
      "stretch_left",
      "nmn_on",
      "nmn_on_left",
      "nmn_on1",
      "nmn_on1_left",
      "nmn-stand",
      "nmn-stand_left",
      "nmn-trot",
      "nmn-trot_left",
      "nmn-open",
      "nmn-open_left",
      "nmn-stand2",
      "nmn-stand2_left",
      "nmn-close",
      "nmn-close_left",
      "nmn-open2",
      "nmn-open2_left",
      "nmn-scared",
      "nmn-scared_left",
      "nmn-close2",
      "nmn-close2_left",
      "nmn_off",
      "nmn_off_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "horn0",
      "horn0_left",
      "horn1",
      "horn1_left",
      "horn2",
      "horn2_left",
      "sitting",
      "sitting_left",
      "stretch",
      "stretch_left",
      "nmn_on",
      "nmn_on_left",
      "nmn_on1",
      "nmn_on1_left",
      "nmn-stand",
      "nmn-stand_left",
      "nmn-trot",
      "nmn-trot_left",
      "nmn-open",
      "nmn-open_left",
      "nmn-stand2",
      "nmn-stand2_left",
      "nmn-close",
      "nmn-close_left",
      "nmn-open2",
      "nmn-open2_left",
      "nmn-scared",
      "nmn-scared_left",
      "nmn-close2",
      "nmn-close2_left",
      "nmn_off",
      "nmn_off_left",
    },
    trot = {},
    trot_left = {},
    horn0 = {
      "stand",
      "stand_left",
      "horn1",
    },
    horn0_left = {
      "stand",
      "stand_left",
      "horn1",
    },
    horn1 = {
      "stand",
      "stand_left",
      "horn2",
    },
    horn1_left = {
      "stand",
      "stand_left",
      "horn2",
    },
    horn2 = {
      "stand",
      "stand_left",
    },
    horn2_left = {
      "stand",
      "stand_left",
    },
    sitting = {
      "stand",
      "stand_left",
    },
    sitting_left = {
      "stand",
      "stand_left",
    },
    stretch = {
      "stand",
      "stand_left",
    },
    stretch_left = {
      "stand",
      "stand_left",
    },
    nmn_on = {
      "stand",
      "stand_left",
      "NMN_on1",
    },
    nmn_on_left = {
      "stand",
      "stand_left",
      "NMN_on1",
    },
    nmn_on1 = {
      "stand",
      "stand_left",
      "nmn-stand",
    },
    nmn_on1_left = {
      "stand",
      "stand_left",
      "nmn-stand",
    },
    ["nmn-stand"] = {
      "stand",
      "stand_left",
    },
    ["nmn-stand_left"] = {
      "stand",
      "stand_left",
    },
    ["nmn-trot"] = {
      "stand",
      "stand_left",
    },
    ["nmn-trot_left"] = {
      "stand",
      "stand_left",
    },
    ["nmn-open"] = {
      "stand",
      "stand_left",
      "nmn-stand2",
    },
    ["nmn-open_left"] = {
      "stand",
      "stand_left",
      "nmn-stand2",
    },
    ["nmn-stand2"] = {
      "stand",
      "stand_left",
      "nmn-close",
    },
    ["nmn-stand2_left"] = {
      "stand",
      "stand_left",
      "nmn-close",
    },
    ["nmn-close"] = {
      "stand",
      "stand_left",
    },
    ["nmn-close_left"] = {
      "stand",
      "stand_left",
    },
    ["nmn-open2"] = {
      "stand",
      "stand_left",
      "nmn-scared",
    },
    ["nmn-open2_left"] = {
      "stand",
      "stand_left",
      "nmn-scared",
    },
    ["nmn-scared"] = {
      "stand",
      "stand_left",
      "nmn-close2",
    },
    ["nmn-scared_left"] = {
      "stand",
      "stand_left",
      "nmn-close2",
    },
    ["nmn-close2"] = {
      "stand",
      "stand_left",
    },
    ["nmn-close2_left"] = {
      "stand",
      "stand_left",
    },
    nmn_off = {
      "stand",
      "stand_left",
    },
    nmn_off_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "horn0",
    "horn0_left",
    "horn1",
    "horn1_left",
    "horn2",
    "horn2_left",
    "sitting",
    "sitting_left",
    "stretch",
    "stretch_left",
    "nmn_on",
    "nmn_on_left",
    "nmn_on1",
    "nmn_on1_left",
    "nmn-stand",
    "nmn-stand_left",
    "nmn-trot",
    "nmn-trot_left",
    "nmn-open",
    "nmn-open_left",
    "nmn-stand2",
    "nmn-stand2_left",
    "nmn-close",
    "nmn-close_left",
    "nmn-open2",
    "nmn-open2_left",
    "nmn-scared",
    "nmn-scared_left",
    "nmn-close2",
    "nmn-close2_left",
    "nmn_off",
    "nmn_off_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {},
      fast = {
        "gallop",
      },
      slow = {},
    },
    left = {
      normal = {
        "gallop_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {},
    },
  },
}