return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "stand wing",
      "stand wing_left",
      "trot wing blink",
      "trot wing blink_left",
      "trot wing",
      "trot wing_left",
      "hover",
      "hover_left",
      "trot blink",
      "trot blink_left",
      "sit",
      "sit_left",
      "sleep",
      "sleep_left",
      "good pace",
      "good pace_left",
      "training",
      "training_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "stand wing",
      "stand wing_left",
      "trot wing blink",
      "trot wing blink_left",
      "trot wing",
      "trot wing_left",
      "hover",
      "hover_left",
      "trot blink",
      "trot blink_left",
      "sit",
      "sit_left",
      "sleep",
      "sleep_left",
      "good pace",
      "good pace_left",
      "training",
      "training_left",
    },
    fly = {
      "stand",
      "stand_left",
    },
    fly_left = {
      "stand",
      "stand_left",
    },
    ["stand wing"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
      "trot wing blink",
      "trot wing blink_left",
      "trot wing",
      "trot wing_left",
      "hover",
      "hover_left",
      "trot blink",
      "trot blink_left",
      "sit",
      "sit_left",
      "sleep",
      "sleep_left",
      "good pace",
      "good pace_left",
      "training",
      "training_left",
    },
    ["stand wing_left"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
      "trot wing blink",
      "trot wing blink_left",
      "trot wing",
      "trot wing_left",
      "hover",
      "hover_left",
      "trot blink",
      "trot blink_left",
      "sit",
      "sit_left",
      "sleep",
      "sleep_left",
      "good pace",
      "good pace_left",
      "training",
      "training_left",
    },
    ["trot wing blink"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    ["trot wing blink_left"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    ["trot wing"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    ["trot wing_left"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    hover = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    hover_left = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    ["trot blink"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    ["trot blink_left"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    trot = {},
    trot_left = {},
    sit = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    sit_left = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    sleep = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
      "sit",
    },
    sleep_left = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
      "sit",
    },
    ["good pace"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    ["good pace_left"] = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    training = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
    training_left = {
      "stand",
      "stand_left",
      "stand wing",
      "stand wing_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "stand wing",
    "stand wing_left",
    "trot wing blink",
    "trot wing blink_left",
    "trot wing",
    "trot wing_left",
    "hover",
    "hover_left",
    "trot blink",
    "trot blink_left",
    "sit",
    "sit_left",
    "sleep",
    "sleep_left",
    "good pace",
    "good pace_left",
    "training",
    "training_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
      },
      fast = {
        "gallop",
      },
      slow = {
        "fly",
      },
    },
    left = {
      normal = {
        "fly_left",
        "gallop_left",
      },
      fast = {
        "fly_left",
        "gallop_left",
      },
      slow = {
        "fly_left",
      },
    },
  },
}