return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "tailwhip",
      "tailwhip_left",
      "tailwhip2",
      "tailwhip2_left",
      "pose",
      "pose_left",
      "walk",
      "walk_left",
      "walk2",
      "walk2_left",
      "fly",
      "fly_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "tailwhip",
      "tailwhip_left",
      "tailwhip2",
      "tailwhip2_left",
      "pose",
      "pose_left",
      "walk",
      "walk_left",
      "walk2",
      "walk2_left",
      "fly",
      "fly_left",
    },
    stand2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "tailwhip",
      "tailwhip_left",
      "tailwhip2",
      "tailwhip2_left",
      "pose",
      "pose_left",
      "walk",
      "walk_left",
      "walk2",
      "walk2_left",
      "fly",
      "fly_left",
    },
    stand2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "tailwhip",
      "tailwhip_left",
      "tailwhip2",
      "tailwhip2_left",
      "pose",
      "pose_left",
      "walk",
      "walk_left",
      "walk2",
      "walk2_left",
      "fly",
      "fly_left",
    },
    tailwhip = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    tailwhip_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    tailwhip2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    tailwhip2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    pose = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    pose_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    walk = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    walk2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "fly",
      "fly_left",
    },
    walk2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "fly",
      "fly_left",
    },
    fly = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "walk",
      "walk_left",
      "walk2",
      "walk2_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "walk",
      "walk_left",
      "walk2",
      "walk2_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "stand2",
    "stand2_left",
    "tailwhip",
    "tailwhip_left",
    "tailwhip2",
    "tailwhip2_left",
    "pose",
    "pose_left",
    "walk2",
    "walk2_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
        "fly",
      },
      fast = {
        "walk",
        "fly",
      },
      slow = {
        "walk",
        "fly",
      },
    },
    left = {
      normal = {
        "walk_left",
        "fly_left",
      },
      fast = {
        "walk_left",
        "fly_left",
      },
      slow = {
        "walk_left",
        "fly_left",
      },
    },
  },
}