return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "admire_rarity_start",
      "admire_rarity_start_left",
      "admire_rarity",
      "admire_rarity_left",
      "follow_rarity",
      "follow_rarity_left",
      "door",
      "stand2",
      "stand2_left",
      "moustache_end",
      "moustache_end_left",
      "moustache_1",
      "moustache_1_left",
      "moustache_2",
      "moustache_2_left",
      "moustache_3",
      "moustache_3_left",
      "moustache_4",
      "moustache_4_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "admire_rarity_start",
      "admire_rarity_start_left",
      "admire_rarity",
      "admire_rarity_left",
      "follow_rarity",
      "follow_rarity_left",
      "door",
      "stand2",
      "stand2_left",
      "moustache_end",
      "moustache_end_left",
      "moustache_1",
      "moustache_1_left",
      "moustache_2",
      "moustache_2_left",
      "moustache_3",
      "moustache_3_left",
      "moustache_4",
      "moustache_4_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    admire_rarity_start = {
      "stand",
      "stand_left",
      "Admire_Rarity",
    },
    admire_rarity_start_left = {
      "stand",
      "stand_left",
      "Admire_Rarity",
    },
    admire_rarity = {
      "stand",
      "stand_left",
    },
    admire_rarity_left = {
      "stand",
      "stand_left",
    },
    follow_rarity = {
      "stand",
      "stand_left",
    },
    follow_rarity_left = {
      "stand",
      "stand_left",
    },
    door = {
      "stand",
      "stand_left",
    },
    stand2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_end",
      "moustache_end_left",
      "moustache_1",
      "moustache_1_left",
      "moustache_2",
      "moustache_2_left",
      "moustache_3",
      "moustache_3_left",
      "moustache_4",
      "moustache_4_left",
    },
    stand2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_end",
      "moustache_end_left",
      "moustache_1",
      "moustache_1_left",
      "moustache_2",
      "moustache_2_left",
      "moustache_3",
      "moustache_3_left",
      "moustache_4",
      "moustache_4_left",
    },
    moustache_end = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    moustache_end_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
    },
    moustache_1 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_2",
    },
    moustache_1_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_2",
    },
    moustache_2 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_3",
    },
    moustache_2_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_3",
    },
    moustache_3 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_4",
    },
    moustache_3_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_4",
    },
    moustache_4 = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_end",
    },
    moustache_4_left = {
      "stand",
      "stand_left",
      "stand2",
      "stand2_left",
      "moustache_end",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "admire_rarity_start",
    "admire_rarity_start_left",
    "admire_rarity",
    "admire_rarity_left",
    "follow_rarity",
    "follow_rarity_left",
    "door",
    "stand2",
    "stand2_left",
    "moustache_end",
    "moustache_end_left",
    "moustache_1",
    "moustache_1_left",
    "moustache_2",
    "moustache_2_left",
    "moustache_3",
    "moustache_3_left",
    "moustache_4",
    "moustache_4_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "walk",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "walk_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}