return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "dash",
      "dash_left",
      "walk",
      "walk_left",
      "goggles",
      "goggles_left",
      "flight",
      "flight_left",
      "wonderbolts",
      "wonderbolts_left",
      "wonderbolts_1",
      "wonderbolts_1_left",
      "stand-nosuit",
      "stand-nosuit_left",
      "fly-nosuit",
      "fly-nosuit_left",
      "dash-nosuit",
      "dash-nosuit_left",
      "walk-nosuit",
      "walk-nosuit_left",
      "remove-suit",
      "remove-suit_left",
      "get-dressed",
      "get-dressed_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "dash",
      "dash_left",
      "walk",
      "walk_left",
      "goggles",
      "goggles_left",
      "flight",
      "flight_left",
      "wonderbolts",
      "wonderbolts_left",
      "wonderbolts_1",
      "wonderbolts_1_left",
      "stand-nosuit",
      "stand-nosuit_left",
      "fly-nosuit",
      "fly-nosuit_left",
      "dash-nosuit",
      "dash-nosuit_left",
      "walk-nosuit",
      "walk-nosuit_left",
      "remove-suit",
      "remove-suit_left",
      "get-dressed",
      "get-dressed_left",
    },
    fly = {
      "stand",
      "stand_left",
    },
    fly_left = {
      "stand",
      "stand_left",
    },
    dash = {
      "stand",
      "stand_left",
    },
    dash_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    goggles = {
      "stand",
      "stand_left",
      "flight",
    },
    goggles_left = {
      "stand",
      "stand_left",
      "flight",
    },
    flight = {
      "stand",
      "stand_left",
    },
    flight_left = {
      "stand",
      "stand_left",
    },
    wonderbolts = {
      "stand",
      "stand_left",
      "wonderbolts_1",
    },
    wonderbolts_left = {
      "stand",
      "stand_left",
      "wonderbolts_1",
    },
    wonderbolts_1 = {
      "stand",
      "stand_left",
    },
    wonderbolts_1_left = {
      "stand",
      "stand_left",
    },
    ["stand-nosuit"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
      "fly-nosuit",
      "fly-nosuit_left",
      "dash-nosuit",
      "dash-nosuit_left",
      "walk-nosuit",
      "walk-nosuit_left",
      "remove-suit",
      "remove-suit_left",
      "get-dressed",
      "get-dressed_left",
    },
    ["stand-nosuit_left"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
      "fly-nosuit",
      "fly-nosuit_left",
      "dash-nosuit",
      "dash-nosuit_left",
      "walk-nosuit",
      "walk-nosuit_left",
      "remove-suit",
      "remove-suit_left",
      "get-dressed",
      "get-dressed_left",
    },
    ["fly-nosuit"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["fly-nosuit_left"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["dash-nosuit"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["dash-nosuit_left"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["walk-nosuit"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["walk-nosuit_left"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["remove-suit"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["remove-suit_left"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["get-dressed"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
    ["get-dressed_left"] = {
      "stand",
      "stand_left",
      "stand-nosuit",
      "stand-nosuit_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "dash",
    "dash_left",
    "goggles",
    "goggles_left",
    "flight",
    "flight_left",
    "wonderbolts",
    "wonderbolts_left",
    "wonderbolts_1",
    "wonderbolts_1_left",
    "stand-nosuit",
    "stand-nosuit_left",
    "fly-nosuit",
    "fly-nosuit_left",
    "dash-nosuit",
    "dash-nosuit_left",
    "walk-nosuit",
    "walk-nosuit_left",
    "remove-suit",
    "remove-suit_left",
    "get-dressed",
    "get-dressed_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
        "walk",
      },
      fast = {
        "fly",
        "walk",
      },
      slow = {
        "fly",
        "walk",
      },
    },
    left = {
      normal = {
        "fly_left",
        "walk_left",
      },
      fast = {
        "fly_left",
        "walk_left",
      },
      slow = {
        "fly_left",
        "walk_left",
      },
    },
  },
}