return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "remove_robe",
      "remove_robe_left",
      "stand1",
      "stand1_left",
      "walking1",
      "walking1_left",
      "wear_robe",
      "wear_robe_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "remove_robe",
      "remove_robe_left",
      "stand1",
      "stand1_left",
      "walking1",
      "walking1_left",
      "wear_robe",
      "wear_robe_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    remove_robe = {
      "stand",
      "stand_left",
      "stand1",
    },
    remove_robe_left = {
      "stand",
      "stand_left",
      "stand1",
    },
    stand1 = {
      "stand",
      "stand_left",
      "stand1",
      "stand1_left",
      "walking1",
      "walking1_left",
      "wear_robe",
      "wear_robe_left",
    },
    stand1_left = {
      "stand",
      "stand_left",
      "stand1",
      "stand1_left",
      "walking1",
      "walking1_left",
      "wear_robe",
      "wear_robe_left",
    },
    walking1 = {
      "stand",
      "stand_left",
      "stand1",
      "stand1_left",
    },
    walking1_left = {
      "stand",
      "stand_left",
      "stand1",
      "stand1_left",
    },
    wear_robe = {
      "stand",
      "stand_left",
      "stand1",
      "stand1_left",
    },
    wear_robe_left = {
      "stand",
      "stand_left",
      "stand1",
      "stand1_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "remove_robe",
    "remove_robe_left",
    "stand1",
    "stand1_left",
    "walking1",
    "walking1_left",
    "wear_robe",
    "wear_robe_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "walk",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "walk_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}