return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly_upside",
      "fly_upside_left",
      "fly_up",
      "fly_up_left",
      "fly",
      "fly_left",
      "hummingbird",
      "hummingbird_left",
      "dance_tongue",
      "dance_tongue_left",
      "backtrack",
      "backtrack_left",
      "get-dressed",
      "get-dressed_left",
      "uniform_stand",
      "uniform_stand_left",
      "uniform_fly",
      "uniform_fly_left",
      "uniform_dash",
      "uniform_dash_left",
      "uniform_walk",
      "uniform_walk_left",
      "undress",
      "undress_left",
      "wonderbolts_1",
      "wonderbolts_1_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly_upside",
      "fly_upside_left",
      "fly_up",
      "fly_up_left",
      "fly",
      "fly_left",
      "hummingbird",
      "hummingbird_left",
      "dance_tongue",
      "dance_tongue_left",
      "backtrack",
      "backtrack_left",
      "get-dressed",
      "get-dressed_left",
      "uniform_stand",
      "uniform_stand_left",
      "uniform_fly",
      "uniform_fly_left",
      "uniform_dash",
      "uniform_dash_left",
      "uniform_walk",
      "uniform_walk_left",
      "undress",
      "undress_left",
      "wonderbolts_1",
      "wonderbolts_1_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "fly",
      "fly_left",
    },
    fly_upside = {
      "stand",
      "stand_left",
    },
    fly_upside_left = {
      "stand",
      "stand_left",
    },
    fly_up = {
      "stand",
      "stand_left",
    },
    fly_up_left = {
      "stand",
      "stand_left",
    },
    fly = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    hummingbird = {
      "stand",
      "stand_left",
    },
    hummingbird_left = {
      "stand",
      "stand_left",
    },
    dance_tongue = {
      "stand",
      "stand_left",
    },
    dance_tongue_left = {
      "stand",
      "stand_left",
    },
    backtrack = {
      "stand",
      "stand_left",
    },
    backtrack_left = {
      "stand",
      "stand_left",
    },
    ["get-dressed"] = {
      "stand",
      "stand_left",
      "uniform_stand",
    },
    ["get-dressed_left"] = {
      "stand",
      "stand_left",
      "uniform_stand",
    },
    uniform_stand = {
      "stand",
      "stand_left",
    },
    uniform_stand_left = {
      "stand",
      "stand_left",
    },
    uniform_fly = {
      "stand",
      "stand_left",
    },
    uniform_fly_left = {
      "stand",
      "stand_left",
    },
    uniform_dash = {
      "stand",
      "stand_left",
    },
    uniform_dash_left = {
      "stand",
      "stand_left",
    },
    uniform_walk = {
      "stand",
      "stand_left",
    },
    uniform_walk_left = {
      "stand",
      "stand_left",
    },
    undress = {
      "stand",
      "stand_left",
    },
    undress_left = {
      "stand",
      "stand_left",
    },
    wonderbolts_1 = {
      "stand",
      "stand_left",
    },
    wonderbolts_1_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "fly_upside",
    "fly_upside_left",
    "fly_up",
    "fly_up_left",
    "hummingbird",
    "hummingbird_left",
    "dance_tongue",
    "dance_tongue_left",
    "backtrack",
    "backtrack_left",
    "get-dressed",
    "get-dressed_left",
    "uniform_stand",
    "uniform_stand_left",
    "uniform_fly",
    "uniform_fly_left",
    "uniform_dash",
    "uniform_dash_left",
    "uniform_walk",
    "uniform_walk_left",
    "undress",
    "undress_left",
    "wonderbolts_1",
    "wonderbolts_1_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
        "fly",
      },
      fast = {
        "walk",
        "fly",
      },
      slow = {
        "walk",
        "fly",
      },
    },
    left = {
      normal = {
        "walk_left",
        "fly_left",
      },
      fast = {
        "walk_left",
        "fly_left",
      },
      slow = {
        "walk_left",
        "fly_left",
      },
    },
  },
}