return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "sit",
      "sit_left",
      "fly",
      "fly_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "look",
      "look_left",
      "scoot",
      "scoot_left",
      "happy_jump",
      "happy_jump_left",
      "skip",
      "skip_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "sit",
      "sit_left",
      "fly",
      "fly_left",
      "sleep",
      "sleep_left",
      "walk",
      "walk_left",
      "look",
      "look_left",
      "scoot",
      "scoot_left",
      "happy_jump",
      "happy_jump_left",
      "skip",
      "skip_left",
    },
    sit = {
      "stand",
      "stand_left",
    },
    sit_left = {
      "stand",
      "stand_left",
    },
    trot = {
      "gallop",
      "gallop_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
    },
    trot_left = {
      "gallop",
      "gallop_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
    },
    gallop = {
      "trot",
      "trot_left",
    },
    gallop_left = {
      "trot",
      "trot_left",
    },
    fly = {
      "stand",
      "stand_left",
      "trot",
      "trot_left",
    },
    fly_left = {
      "stand",
      "stand_left",
      "trot",
      "trot_left",
    },
    sleep = {
      "stand",
      "stand_left",
    },
    sleep_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "trot",
      "trot_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "trot",
      "trot_left",
      "walk",
      "walk_left",
    },
    look = {
      "stand",
      "stand_left",
    },
    look_left = {
      "stand",
      "stand_left",
    },
    scoot = {
      "stand",
      "stand_left",
    },
    scoot_left = {
      "stand",
      "stand_left",
    },
    happy_jump = {
      "stand",
      "stand_left",
    },
    happy_jump_left = {
      "stand",
      "stand_left",
    },
    skip = {
      "stand",
      "stand_left",
    },
    skip_left = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "sit",
    "sit_left",
    "sleep",
    "sleep_left",
    "look",
    "look_left",
    "scoot",
    "scoot_left",
    "happy_jump",
    "happy_jump_left",
    "skip",
    "skip_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
        "walk",
      },
      fast = {
        "gallop",
      },
      slow = {
        "fly",
        "walk",
      },
    },
    left = {
      normal = {
        "gallop_left",
        "fly_left",
        "walk_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {
        "fly_left",
        "walk_left",
      },
    },
  },
}