return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "get clothes",
      "get clothes_left",
      "stand 1",
      "stand 1_left",
      "trot 1",
      "trot 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "get clothes",
      "get clothes_left",
      "stand 1",
      "stand 1_left",
      "trot 1",
      "trot 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    trot = {},
    trot_left = {},
    ["get clothes"] = {
      "stand",
      "stand_left",
      "stand 1",
    },
    ["get clothes_left"] = {
      "stand",
      "stand_left",
      "stand 1",
    },
    ["stand 1"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
      "trot 1",
      "trot 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    ["stand 1_left"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
      "trot 1",
      "trot 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    ["trot 1"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["trot 1_left"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["remove clothes"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["remove clothes_left"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "get clothes",
    "get clothes_left",
    "stand 1",
    "stand 1_left",
    "trot 1",
    "trot 1_left",
    "remove clothes",
    "remove clothes_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {},
      fast = {
        "gallop",
      },
      slow = {},
    },
    left = {
      normal = {
        "gallop_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {},
    },
  },
}