return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
      "get clothes",
      "get clothes_left",
      "stand 1",
      "stand 1_left",
      "fly 1",
      "fly 1_left",
      "walk 1",
      "walk 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "fly",
      "fly_left",
      "walk",
      "walk_left",
      "get clothes",
      "get clothes_left",
      "stand 1",
      "stand 1_left",
      "fly 1",
      "fly 1_left",
      "walk 1",
      "walk 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    fly = {
      "stand",
      "stand_left",
    },
    fly_left = {
      "stand",
      "stand_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    ["get clothes"] = {
      "stand",
      "stand_left",
      "stand 1",
    },
    ["get clothes_left"] = {
      "stand",
      "stand_left",
      "stand 1",
    },
    ["stand 1"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
      "fly 1",
      "fly 1_left",
      "walk 1",
      "walk 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    ["stand 1_left"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
      "fly 1",
      "fly 1_left",
      "walk 1",
      "walk 1_left",
      "remove clothes",
      "remove clothes_left",
    },
    ["fly 1"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["fly 1_left"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["walk 1"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["walk 1_left"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["remove clothes"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
    ["remove clothes_left"] = {
      "stand",
      "stand_left",
      "stand 1",
      "stand 1_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "get clothes",
    "get clothes_left",
    "stand 1",
    "stand 1_left",
    "fly 1",
    "fly 1_left",
    "walk 1",
    "walk 1_left",
    "remove clothes",
    "remove clothes_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "fly",
        "walk",
      },
      fast = {
        "fly",
        "walk",
      },
      slow = {
        "fly",
        "walk",
      },
    },
    left = {
      normal = {
        "fly_left",
        "walk_left",
      },
      fast = {
        "fly_left",
        "walk_left",
      },
      slow = {
        "fly_left",
        "walk_left",
      },
    },
  },
}