return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "sit",
      "sit_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "flowers",
      "flowers_left",
      "stand-naked",
      "stand-naked_left",
      "walking-naked",
      "walking-naked_left",
      "take_off_cape",
      "take_off_cape_left",
      "put_on_cape",
      "put_on_cape_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "sit",
      "sit_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "flowers",
      "flowers_left",
      "stand-naked",
      "stand-naked_left",
      "walking-naked",
      "walking-naked_left",
      "take_off_cape",
      "take_off_cape_left",
      "put_on_cape",
      "put_on_cape_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
    },
    sit = {
      "stand",
      "stand_left",
    },
    sit_left = {
      "stand",
      "stand_left",
    },
    stand_fireworks = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "flowers",
      "flowers_left",
      "stand-naked",
      "stand-naked_left",
      "walking-naked",
      "walking-naked_left",
      "take_off_cape",
      "take_off_cape_left",
      "put_on_cape",
      "put_on_cape_left",
    },
    stand_fireworks_left = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "flowers",
      "flowers_left",
      "stand-naked",
      "stand-naked_left",
      "walking-naked",
      "walking-naked_left",
      "take_off_cape",
      "take_off_cape_left",
      "put_on_cape",
      "put_on_cape_left",
    },
    flowers = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
    },
    flowers_left = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
    },
    ["stand-naked"] = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
      "walking-naked",
      "walking-naked_left",
      "take_off_cape",
      "take_off_cape_left",
      "put_on_cape",
      "put_on_cape_left",
    },
    ["stand-naked_left"] = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
      "walking-naked",
      "walking-naked_left",
      "take_off_cape",
      "take_off_cape_left",
      "put_on_cape",
      "put_on_cape_left",
    },
    ["walking-naked"] = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
    },
    ["walking-naked_left"] = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
    },
    take_off_cape = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
    },
    take_off_cape_left = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
    },
    put_on_cape = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
    },
    put_on_cape_left = {
      "stand",
      "stand_left",
      "stand_fireworks",
      "stand_fireworks_left",
      "stand-naked",
      "stand-naked_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "sit",
    "sit_left",
    "stand_fireworks",
    "stand_fireworks_left",
    "flowers",
    "flowers_left",
    "stand-naked",
    "stand-naked_left",
    "walking-naked",
    "walking-naked_left",
    "take_off_cape",
    "take_off_cape_left",
    "put_on_cape",
    "put_on_cape_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "walk",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "walk_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}