return {
  next_actions = {
    stand = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "take_control_walk",
      "take_control_walk_left",
      "take_control_walk2",
      "take_control_walk2_left",
      "warp1",
      "warp1_left",
      "warp2",
      "warp3",
      "warp3_left",
      "read",
      "theme 1",
      "theme 1_left",
      "theme 2",
      "theme 2_left",
      "theme 3",
      "theme 3_left",
      "theme 4",
      "theme 4_left",
      "theme 5",
      "theme 5_left",
      "galla_dress",
      "galla_dress_left",
      "baloon",
      "baloon_left",
      "rage",
      "rage_left",
      "breakdown",
      "breakdown_left",
      "discorded",
      "discorded_left",
      "pinkaport",
      "pinkaport_left",
      "twologht",
      "twologht_left",
      "conga",
      "conga_left",
      "drag",
      "drag_left",
      "flowing_mane",
      "flowing_mane_left",
      "ride",
      "ride_left",
      "crystallized",
      "crystallized_left",
      "party_hard",
      "party_hard_left",
      "starswirl",
      "starswirl_left",
      "banner again",
      "banner again_left",
    },
    stand_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "take_control_walk",
      "take_control_walk_left",
      "take_control_walk2",
      "take_control_walk2_left",
      "warp1",
      "warp1_left",
      "warp2",
      "warp3",
      "warp3_left",
      "read",
      "theme 1",
      "theme 1_left",
      "theme 2",
      "theme 2_left",
      "theme 3",
      "theme 3_left",
      "theme 4",
      "theme 4_left",
      "theme 5",
      "theme 5_left",
      "galla_dress",
      "galla_dress_left",
      "baloon",
      "baloon_left",
      "rage",
      "rage_left",
      "breakdown",
      "breakdown_left",
      "discorded",
      "discorded_left",
      "pinkaport",
      "pinkaport_left",
      "twologht",
      "twologht_left",
      "conga",
      "conga_left",
      "drag",
      "drag_left",
      "flowing_mane",
      "flowing_mane_left",
      "ride",
      "ride_left",
      "crystallized",
      "crystallized_left",
      "party_hard",
      "party_hard_left",
      "starswirl",
      "starswirl_left",
      "banner again",
      "banner again_left",
    },
    walk = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
    },
    walk_left = {
      "stand",
      "stand_left",
      "walk",
      "walk_left",
      "gallop",
      "gallop_left",
    },
    take_control_walk = {
      "stand",
      "stand_left",
    },
    take_control_walk_left = {
      "stand",
      "stand_left",
    },
    take_control_walk2 = {
      "stand",
      "stand_left",
    },
    take_control_walk2_left = {
      "stand",
      "stand_left",
    },
    warp1 = {
      "stand",
      "stand_left",
      "warp2",
    },
    warp1_left = {
      "stand",
      "stand_left",
      "warp2",
    },
    warp2 = {
      "stand",
      "stand_left",
      "warp3",
    },
    warp3 = {
      "stand",
      "stand_left",
    },
    warp3_left = {
      "stand",
      "stand_left",
    },
    read = {
      "stand",
      "stand_left",
    },
    ["theme 1"] = {
      "stand",
      "stand_left",
      "theme 2",
    },
    ["theme 1_left"] = {
      "stand",
      "stand_left",
      "theme 2",
    },
    ["theme 2"] = {
      "stand",
      "stand_left",
      "theme 3",
    },
    ["theme 2_left"] = {
      "stand",
      "stand_left",
      "theme 3",
    },
    ["theme 3"] = {
      "stand",
      "stand_left",
      "theme 4",
    },
    ["theme 3_left"] = {
      "stand",
      "stand_left",
      "theme 4",
    },
    ["theme 4"] = {
      "stand",
      "stand_left",
      "theme 5",
    },
    ["theme 4_left"] = {
      "stand",
      "stand_left",
      "theme 5",
    },
    ["theme 5"] = {
      "stand",
      "stand_left",
    },
    ["theme 5_left"] = {
      "stand",
      "stand_left",
    },
    galla_dress = {
      "stand",
      "stand_left",
    },
    galla_dress_left = {
      "stand",
      "stand_left",
    },
    baloon = {
      "stand",
      "stand_left",
    },
    baloon_left = {
      "stand",
      "stand_left",
    },
    rage = {
      "stand",
      "stand_left",
    },
    rage_left = {
      "stand",
      "stand_left",
    },
    gallop = {
      "walk",
      "walk_left",
    },
    gallop_left = {
      "walk",
      "walk_left",
    },
    breakdown = {
      "stand",
      "stand_left",
    },
    breakdown_left = {
      "stand",
      "stand_left",
    },
    discorded = {
      "stand",
      "stand_left",
    },
    discorded_left = {
      "stand",
      "stand_left",
    },
    pinkaport = {
      "stand",
      "stand_left",
    },
    pinkaport_left = {
      "stand",
      "stand_left",
    },
    twologht = {
      "stand",
      "stand_left",
    },
    twologht_left = {
      "stand",
      "stand_left",
    },
    conga = {
      "stand",
      "stand_left",
    },
    conga_left = {
      "stand",
      "stand_left",
    },
    drag = {
      "stand",
      "stand_left",
    },
    drag_left = {
      "stand",
      "stand_left",
    },
    flowing_mane = {
      "stand",
      "stand_left",
    },
    flowing_mane_left = {
      "stand",
      "stand_left",
    },
    ride = {
      "stand",
      "stand_left",
    },
    ride_left = {
      "stand",
      "stand_left",
    },
    crystallized = {
      "stand",
      "stand_left",
    },
    crystallized_left = {
      "stand",
      "stand_left",
    },
    party_hard = {
      "stand",
      "stand_left",
    },
    party_hard_left = {
      "stand",
      "stand_left",
    },
    starswirl = {
      "stand",
      "stand_left",
    },
    starswirl_left = {
      "stand",
      "stand_left",
    },
    ["banner again"] = {
      "stand",
      "stand_left",
    },
    ["banner again_left"] = {
      "stand",
      "stand_left",
    },
  },
  idle_actions = {
    "stand",
    "stand_left",
    "take_control_walk",
    "take_control_walk_left",
    "take_control_walk2",
    "take_control_walk2_left",
    "warp1",
    "warp1_left",
    "warp2",
    "warp3",
    "warp3_left",
    "read",
    "theme 1",
    "theme 1_left",
    "theme 2",
    "theme 2_left",
    "theme 3",
    "theme 3_left",
    "theme 4",
    "theme 4_left",
    "theme 5",
    "theme 5_left",
    "galla_dress",
    "galla_dress_left",
    "baloon",
    "baloon_left",
    "rage",
    "rage_left",
    "breakdown",
    "breakdown_left",
    "discorded",
    "discorded_left",
    "pinkaport",
    "pinkaport_left",
    "twologht",
    "twologht_left",
    "conga",
    "conga_left",
    "drag",
    "drag_left",
    "flowing_mane",
    "flowing_mane_left",
    "ride",
    "ride_left",
    "crystallized",
    "crystallized_left",
    "party_hard",
    "party_hard_left",
    "starswirl",
    "starswirl_left",
    "banner again",
    "banner again_left",
  },
  first_action = "stand",
  movements = {
    right = {
      normal = {
        "walk",
      },
      fast = {
        "gallop",
      },
      slow = {
        "walk",
      },
    },
    left = {
      normal = {
        "walk_left",
      },
      fast = {
        "gallop_left",
      },
      slow = {
        "walk_left",
      },
    },
  },
}